import type { GrammarTopic } from '@/types/grammar';

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  {
    id: 'nouns',
    title: 'Nouns',
    emoji: '🏷️',
    gradient: 'from-blue-400 to-cyan-300',
    tagline: 'Name everything around you!',
    description: 'A noun is a naming word! It names a person, place, animal, or thing.',
    examples: [
      'The **dog** ran fast.',
      'We live in a **city**.',
      'My **teacher** is kind.',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'nouns-1',
        type: 'identify',
        instruction: 'Tap the NOUN (naming word) in this sentence!',
        sentence: 'The rabbit ate a carrot.',
        options: ['The', 'rabbit', 'ate', 'carrot'],
        correctAnswer: 'rabbit',
        explanation: '🎉 Brilliant! "Rabbit" is a noun — it is the name of an animal! Nouns can be people, places, animals, or things. "Carrot" is also a noun — can you spot it?',
        points: 10,
      },
      {
        id: 'nouns-2',
        type: 'fill-blank',
        instruction: 'Choose the NOUN to complete the sentence!',
        sentence: 'The ___ flew over the rainbow.',
        options: ['dragon', 'shiny', 'quickly', 'very'],
        correctAnswer: 'dragon',
        explanation: '🌟 That\'s right! "Dragon" is a noun — it names a magical creature! Nouns tell us WHAT or WHO the sentence is about. Every sentence needs a noun!',
        points: 10,
      },
      {
        id: 'nouns-3',
        type: 'multiple-choice',
        instruction: 'Which word is a NOUN?',
        sentence: 'Which of these is a naming word?',
        options: ['jump', 'happy', 'castle', 'slowly'],
        correctAnswer: 'castle',
        explanation: '✨ Amazing! "Castle" is a noun — it names a place where kings and queens live! "Jump" is a verb (action), "happy" is an adjective (describing), and "slowly" is an adverb. Nouns are the only naming words!',
        points: 10,
      },
      {
        id: 'nouns-4',
        type: 'identify',
        instruction: 'Tap the NOUN in this sentence!',
        sentence: 'My friend baked a cake.',
        options: ['My', 'friend', 'baked', 'cake'],
        correctAnswer: 'friend',
        explanation: '🎊 Great thinking! "Friend" is a noun — it names a person! "Cake" is also a noun — it names a thing. Sentences can have more than one noun!',
        points: 10,
      },
      {
        id: 'nouns-5',
        type: 'multiple-choice',
        instruction: 'Find the noun in this sentence: "The wizard wore a hat."',
        sentence: 'The wizard wore a hat.',
        options: ['wore', 'wizard', 'The', 'a'],
        correctAnswer: 'wizard',
        explanation: '⭐ Superstar! "Wizard" is a noun — it names a magical person! "Hat" is also a noun in this sentence. You are getting really good at spotting nouns!',
        points: 10,
      },
    ],
  },
  {
    id: 'verbs',
    title: 'Verbs',
    emoji: '⚡',
    gradient: 'from-yellow-400 to-orange-300',
    tagline: 'Action words that make things happen!',
    description: 'A verb is an action word! It tells us what someone or something does.',
    examples: [
      'The cat **jumps** over the fence.',
      'Birds **sing** in the morning.',
      'She **reads** every night.',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'verbs-1',
        type: 'identify',
        instruction: 'Tap the VERB (action word) in this sentence!',
        sentence: 'The monkey climbed the tree.',
        options: ['The', 'monkey', 'climbed', 'tree'],
        correctAnswer: 'climbed',
        explanation: '🎉 You got it! "Climbed" is a verb — it tells us what the monkey DID! Verbs are action words that show what is happening. Every sentence needs a verb!',
        points: 10,
      },
      {
        id: 'verbs-2',
        type: 'fill-blank',
        instruction: 'Choose the VERB to complete the sentence!',
        sentence: 'The puppy ___ in the puddle.',
        options: ['splashed', 'muddy', 'little', 'happily'],
        correctAnswer: 'splashed',
        explanation: '🌊 Wonderful! "Splashed" is a verb — it tells us what the puppy did! Think about what the puppy was doing in the puddle. Verbs show us the action!',
        points: 10,
      },
      {
        id: 'verbs-3',
        type: 'multiple-choice',
        instruction: 'Which word is a VERB (action word)?',
        sentence: 'Which word shows something happening or being done?',
        options: ['purple', 'mountain', 'dances', 'soft'],
        correctAnswer: 'dances',
        explanation: '💃 Fantastic! "Dances" is a verb — it shows an action! "Purple" and "soft" are adjectives (describing words), and "mountain" is a noun (naming word). Verbs always show action or being!',
        points: 10,
      },
      {
        id: 'verbs-4',
        type: 'identify',
        instruction: 'Tap the VERB in this sentence!',
        sentence: 'The fairy sprinkled magic dust.',
        options: ['fairy', 'sprinkled', 'magic', 'dust'],
        correctAnswer: 'sprinkled',
        explanation: '✨ Brilliant! "Sprinkled" is a verb — it shows the action the fairy did! Imagine the fairy sprinkling the dust — that sprinkling is the verb!',
        points: 10,
      },
      {
        id: 'verbs-5',
        type: 'multiple-choice',
        instruction: 'Find the verb in: "The dragon breathes fire."',
        sentence: 'The dragon breathes fire.',
        options: ['dragon', 'The', 'breathes', 'fire'],
        correctAnswer: 'breathes',
        explanation: '🐉 Amazing work! "Breathes" is the verb — it is the action the dragon does! Fire and dragon are nouns (naming words). You are becoming a verb expert!',
        points: 10,
      },
    ],
  },
  {
    id: 'adjectives',
    title: 'Adjectives',
    emoji: '🎨',
    gradient: 'from-pink-400 to-rose-300',
    tagline: 'Describing words that paint a picture!',
    description: 'An adjective is a describing word! It tells us more about a noun.',
    examples: [
      'The **tiny** mouse hid under the bed.',
      'She wore a **sparkly** dress.',
      'We live in a **cozy** house.',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'adjectives-1',
        type: 'identify',
        instruction: 'Tap the ADJECTIVE (describing word) in this sentence!',
        sentence: 'The fluffy cat sat on the mat.',
        options: ['The', 'fluffy', 'cat', 'sat'],
        correctAnswer: 'fluffy',
        explanation: '🎉 Perfect! "Fluffy" is an adjective — it describes what the cat looks like! Adjectives help us picture things in our mind. What colour or size could the cat also be?',
        points: 10,
      },
      {
        id: 'adjectives-2',
        type: 'fill-blank',
        instruction: 'Choose the ADJECTIVE to complete the sentence!',
        sentence: 'The ___ dragon lived in a cave.',
        options: ['enormous', 'eating', 'slowly', 'cave'],
        correctAnswer: 'enormous',
        explanation: '🐲 Excellent! "Enormous" is an adjective — it tells us the SIZE of the dragon! Without adjectives, sentences would be much more boring. Describing words make everything more fun!',
        points: 10,
      },
      {
        id: 'adjectives-3',
        type: 'multiple-choice',
        instruction: 'Which word is an ADJECTIVE (describing word)?',
        sentence: 'Which word describes something?',
        options: ['run', 'tree', 'golden', 'under'],
        correctAnswer: 'golden',
        explanation: '⭐ Superb! "Golden" is an adjective — it describes a colour! "Run" is a verb, "tree" is a noun, and "under" is a preposition. Adjectives make nouns more interesting!',
        points: 10,
      },
      {
        id: 'adjectives-4',
        type: 'identify',
        instruction: 'Tap the ADJECTIVE in this sentence!',
        sentence: 'She found a shiny coin in the garden.',
        options: ['found', 'shiny', 'coin', 'garden'],
        correctAnswer: 'shiny',
        explanation: '💎 Wonderful! "Shiny" is an adjective — it tells us what the coin LOOKS LIKE! We can picture the coin sparkling in the sunlight. Adjectives bring sentences to life!',
        points: 10,
      },
      {
        id: 'adjectives-5',
        type: 'multiple-choice',
        instruction: 'Find the adjective in: "The brave knight saved the princess."',
        sentence: 'The brave knight saved the princess.',
        options: ['knight', 'saved', 'brave', 'princess'],
        correctAnswer: 'brave',
        explanation: '🛡️ Amazing! "Brave" is an adjective — it describes the knight! Now we know what kind of knight he is. Adjectives always describe nouns, so look for a word that tells us more about a person or thing!',
        points: 10,
      },
    ],
  },
  {
    id: 'pronouns',
    title: 'Pronouns',
    emoji: '🔄',
    gradient: 'from-purple-400 to-violet-300',
    tagline: 'Handy swap-in words!',
    description: 'A pronoun takes the place of a noun! Instead of saying a name again, we use I, you, he, she, it, we, or they.',
    examples: [
      '**She** loves to read.',
      '**They** played in the park.',
      '**It** was a sunny day.',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'pronouns-1',
        type: 'identify',
        instruction: 'Tap the PRONOUN in this sentence!',
        sentence: 'He jumped over the puddle.',
        options: ['He', 'jumped', 'over', 'puddle'],
        correctAnswer: 'He',
        explanation: '🎉 Brilliant! "He" is a pronoun — it takes the place of a boy\'s name! Instead of saying "Tom jumped over the puddle," we use "he" so we don\'t have to repeat the name every time!',
        points: 10,
      },
      {
        id: 'pronouns-2',
        type: 'fill-blank',
        instruction: 'Choose the best PRONOUN to replace "Emma" in this sentence!',
        sentence: '___ loves to eat strawberries.',
        options: ['She', 'He', 'It', 'They'],
        correctAnswer: 'She',
        explanation: '🍓 That\'s right! "She" is the correct pronoun for a girl\'s name like Emma! Pronouns are like shortcuts — they help us avoid repeating names over and over again!',
        points: 10,
      },
      {
        id: 'pronouns-3',
        type: 'multiple-choice',
        instruction: 'Which pronoun would replace "the dogs" in a sentence?',
        sentence: 'What pronoun do we use for more than one thing or person?',
        options: ['he', 'she', 'it', 'they'],
        correctAnswer: 'they',
        explanation: '🐕 Excellent! "They" is the pronoun we use when talking about more than one person or animal! We say "the dogs" but then we can say "they" to avoid repeating "the dogs" over and over!',
        points: 10,
      },
      {
        id: 'pronouns-4',
        type: 'identify',
        instruction: 'Tap the PRONOUN in this sentence!',
        sentence: 'We ate pizza for dinner.',
        options: ['We', 'ate', 'pizza', 'dinner'],
        correctAnswer: 'We',
        explanation: '🍕 Perfect! "We" is a pronoun — it means more than one person including yourself! Instead of saying all the names of everyone at dinner, we just say "we." So handy!',
        points: 10,
      },
      {
        id: 'pronouns-5',
        type: 'multiple-choice',
        instruction: 'Which pronoun fills the blank? "The ball rolled away. ___ went down the hill."',
        sentence: 'The ball rolled away. ___ went down the hill.',
        options: ['He', 'She', 'It', 'They'],
        correctAnswer: 'It',
        explanation: '⚽ Wonderful! "It" is the pronoun we use for things (not people)! The ball is a thing, so we say "it" instead of "the ball" again. Pronouns make our sentences sound much smoother!',
        points: 10,
      },
    ],
  },
  {
    id: 'adverbs',
    title: 'Adverbs',
    emoji: '🌊',
    gradient: 'from-teal-400 to-green-300',
    tagline: 'Tell us HOW, WHEN, and WHERE!',
    description: 'An adverb tells us more about a verb! It describes HOW, WHEN, or WHERE something happens.',
    examples: [
      'The turtle walked **slowly**.',
      'She **always** brushes her teeth.',
      'The rabbit ran **away**.',
    ],
    requiredLevel: 1,
    pointsReward: 30,
    exercises: [
      {
        id: 'adverbs-1',
        type: 'identify',
        instruction: 'Tap the ADVERB (tells us HOW something happened) in this sentence!',
        sentence: 'The lion roared loudly.',
        options: ['The', 'lion', 'roared', 'loudly'],
        correctAnswer: 'loudly',
        explanation: '🦁 Brilliant! "Loudly" is an adverb — it tells us HOW the lion roared! Many adverbs end in "-ly" like quietly, quickly, and happily. They describe the action (verb) in the sentence!',
        points: 10,
      },
      {
        id: 'adverbs-2',
        type: 'fill-blank',
        instruction: 'Choose the ADVERB to complete the sentence!',
        sentence: 'The butterfly flew ___ over the flowers.',
        options: ['gracefully', 'butterfly', 'pretty', 'garden'],
        correctAnswer: 'gracefully',
        explanation: '🦋 Amazing! "Gracefully" is an adverb — it tells us HOW the butterfly flew! Can you imagine a butterfly floating gracefully through the air? Adverbs help us picture things more clearly!',
        points: 10,
      },
      {
        id: 'adverbs-3',
        type: 'multiple-choice',
        instruction: 'Which word is an ADVERB?',
        sentence: 'Which word tells us more about HOW, WHEN, or WHERE?',
        options: ['purple', 'gently', 'elephant', 'run'],
        correctAnswer: 'gently',
        explanation: '🌸 Excellent! "Gently" is an adverb — it tells us HOW something is done! "Purple" is an adjective, "elephant" is a noun, and "run" is a verb. Adverbs describe verbs, adjectives, or other adverbs!',
        points: 10,
      },
      {
        id: 'adverbs-4',
        type: 'identify',
        instruction: 'Tap the ADVERB in this sentence!',
        sentence: 'The children played outside.',
        options: ['children', 'played', 'outside', 'The'],
        correctAnswer: 'outside',
        explanation: '🏡 Wonderful! "Outside" is an adverb — it tells us WHERE the children played! Not all adverbs end in "-ly." Words like outside, here, there, and away are also adverbs that tell us WHERE!',
        points: 10,
      },
      {
        id: 'adverbs-5',
        type: 'multiple-choice',
        instruction: 'Find the adverb in: "The puppy quickly ate its food."',
        sentence: 'The puppy quickly ate its food.',
        options: ['puppy', 'quickly', 'food', 'ate'],
        correctAnswer: 'quickly',
        explanation: '🐶 Superstar! "Quickly" is the adverb — it tells us HOW FAST the puppy ate! "Quickly" describes the verb "ate." You are getting so good at finding adverbs!',
        points: 10,
      },
    ],
  },
  {
    id: 'punctuation',
    title: 'Punctuation',
    emoji: '📍',
    gradient: 'from-red-400 to-pink-300',
    tagline: 'Symbols that guide our reading!',
    description: 'Punctuation marks are special symbols that help us read! A full stop ends a sentence. A question mark asks something. An exclamation mark shows excitement!',
    examples: [
      'I love ice cream**.**',
      'What is your name**?**',
      'That was amazing**!**',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'punctuation-1',
        type: 'multiple-choice',
        instruction: 'Which punctuation mark goes at the end of this sentence?',
        sentence: 'The cat sat on the mat',
        options: ['.', '?', '!', ','],
        correctAnswer: '.',
        explanation: '📝 Perfect! A full stop (.) goes at the end of a sentence that is just telling us something! It is like pressing the "stop" button at the end of a thought. Every sentence needs an ending punctuation!',
        points: 10,
      },
      {
        id: 'punctuation-2',
        type: 'multiple-choice',
        instruction: 'Which punctuation mark goes at the end of this sentence?',
        sentence: 'Where does the dragon live',
        options: ['?', '.', '!', ','],
        correctAnswer: '?',
        explanation: '❓ Brilliant! A question mark (?) goes at the end of a question! When we ask something, we always use a question mark. Look for words like "where," "what," "when," and "how" — they often start questions!',
        points: 10,
      },
      {
        id: 'punctuation-3',
        type: 'multiple-choice',
        instruction: 'Which punctuation mark goes at the end of this sentence?',
        sentence: 'Watch out for the monster',
        options: ['!', '.', '?', ','],
        correctAnswer: '!',
        explanation: '❗ Amazing! An exclamation mark (!) goes at the end of a sentence that shows strong feelings or surprise! When we are excited, scared, or shouting a warning, we use an exclamation mark!',
        points: 10,
      },
      {
        id: 'punctuation-4',
        type: 'multiple-choice',
        instruction: 'This sentence is asking something. What punctuation does it need?',
        sentence: 'Can you fly on a broomstick',
        options: ['?', '.', '!', ';'],
        correctAnswer: '?',
        explanation: '🧹 Wonderful! Yes — "Can you fly on a broomstick?" needs a question mark! Sentences that start with "can," "do," "is," "are," or "will" are almost always questions. Great detective work!',
        points: 10,
      },
      {
        id: 'punctuation-5',
        type: 'fix-sentence',
        instruction: 'Which version of this sentence has the CORRECT punctuation?',
        sentence: 'We won the treasure hunt',
        options: [
          'We won the treasure hunt.',
          'We won the treasure hunt?',
          'we won the treasure hunt!',
          'We won the treasure hunt',
        ],
        correctAnswer: 'We won the treasure hunt.',
        explanation: '🏆 Super! The correct version uses a full stop (.) because we are just telling someone what happened. Also notice that sentences always start with a CAPITAL letter! Both the capital letter and the full stop are important!',
        points: 10,
      },
    ],
  },
  {
    id: 'sentences',
    title: 'Sentences',
    emoji: '🔨',
    gradient: 'from-indigo-400 to-blue-300',
    tagline: 'Build complete thoughts!',
    description: 'A sentence is a complete thought! Every sentence has a naming part (subject) and an action part (predicate). It starts with a capital letter and ends with punctuation.',
    examples: [
      '**The dog** barked loudly. (subject + predicate)',
      '**My sister** loves chocolate cake.',
      '**The magic carpet** flew over the mountains.',
    ],
    requiredLevel: 1,
    pointsReward: 30,
    exercises: [
      {
        id: 'sentences-1',
        type: 'multiple-choice',
        instruction: 'Which of these is a COMPLETE sentence?',
        sentence: 'Which one has both a naming part AND an action part?',
        options: [
          'The big red balloon.',
          'Floated away.',
          'The big red balloon floated away.',
          'Floated the balloon.',
        ],
        correctAnswer: 'The big red balloon floated away.',
        explanation: '🎈 Brilliant! "The big red balloon floated away" is a complete sentence — it has a subject (the balloon) and a predicate (floated away)! A sentence needs BOTH parts to make a complete thought!',
        points: 10,
      },
      {
        id: 'sentences-2',
        type: 'sort-words',
        instruction: 'Tap the words in the RIGHT ORDER to make a sentence!',
        sentence: 'the | cat | ate | fish | the',
        options: ['The', 'cat', 'ate', 'the', 'fish'],
        correctAnswer: 'The cat ate the fish',
        explanation: '🐟 Amazing! "The cat ate the fish" is a perfect sentence! It starts with a capital letter, has a subject (the cat) and a verb (ate), and makes complete sense. Well done for putting it all together!',
        points: 10,
      },
      {
        id: 'sentences-3',
        type: 'identify',
        instruction: 'Which word is the SUBJECT (naming part) of this sentence?',
        sentence: 'The wizard cast a spell.',
        options: ['The', 'wizard', 'cast', 'spell'],
        correctAnswer: 'wizard',
        explanation: '🧙 Excellent! "Wizard" is the subject — it is WHO the sentence is about! To find the subject, ask yourself: "WHO or WHAT is doing the action?" The wizard is doing the casting!',
        points: 10,
      },
      {
        id: 'sentences-4',
        type: 'sort-words',
        instruction: 'Tap the words in the RIGHT ORDER to make a sentence!',
        sentence: 'birds | sing | the | trees | in',
        options: ['The', 'birds', 'sing', 'in', 'the', 'trees'],
        correctAnswer: 'The birds sing in the trees',
        explanation: '🐦 Wonderful! "The birds sing in the trees" is a lovely sentence! It starts with "The" (capital T), the birds are the subject, "sing" is the verb, and "in the trees" tells us where. Perfect!',
        points: 10,
      },
      {
        id: 'sentences-5',
        type: 'fix-sentence',
        instruction: 'Which version is a CORRECT sentence?',
        sentence: 'the happy frog jumped high.',
        options: [
          'The happy frog jumped high.',
          'the happy frog jumped high.',
          'The happy frog jumped high',
          'The happy frog. jumped high.',
        ],
        correctAnswer: 'The happy frog jumped high.',
        explanation: '🐸 Superstar! The correct sentence starts with a CAPITAL letter (The) and ends with a full stop (.)! Remember the two golden rules: start with a big letter and end with punctuation. You are a sentence expert!',
        points: 10,
      },
    ],
  },
  {
    id: 'rhyming',
    title: 'Rhyming Words',
    emoji: '🎵',
    gradient: 'from-amber-400 to-yellow-300',
    tagline: 'Words that sing together!',
    description: 'Rhyming words sound the same at the end! Cat rhymes with hat, bat, and mat. Rhyming helps us remember words and makes reading fun!',
    examples: [
      '**Cat** rhymes with **hat** and **bat**.',
      '**Moon** rhymes with **spoon** and **tune**.',
      '**King** rhymes with **ring** and **sing**.',
    ],
    requiredLevel: 0,
    pointsReward: 25,
    exercises: [
      {
        id: 'rhyming-1',
        type: 'multiple-choice',
        instruction: 'Which word RHYMES with "star"?',
        sentence: 'Find the word that has the same ending sound as "star"!',
        options: ['sun', 'car', 'moon', 'sky'],
        correctAnswer: 'car',
        explanation: '⭐ Brilliant! "Car" rhymes with "star" — they both end with the "-ar" sound! Star... car... can you hear it? Rhyming words have the same ending sounds even if they start differently!',
        points: 10,
      },
      {
        id: 'rhyming-2',
        type: 'multiple-choice',
        instruction: 'Which word RHYMES with "cake"?',
        sentence: 'Listen to the ending sound of "cake" — which word matches?',
        options: ['eat', 'bake', 'sweet', 'yummy'],
        correctAnswer: 'bake',
        explanation: '🎂 Wonderful! "Bake" rhymes with "cake" — they both end with the "-ake" sound! Cake... bake... lake... make... there are lots of words that rhyme with cake! Can you think of more?',
        points: 10,
      },
      {
        id: 'rhyming-3',
        type: 'fill-blank',
        instruction: 'Complete the rhyme: "I saw a frog sitting on a ___."',
        sentence: 'I saw a frog sitting on a ___.',
        options: ['log', 'tree', 'pond', 'leaf'],
        correctAnswer: 'log',
        explanation: '🐸 Amazing! "Log" rhymes with "frog" — they both end with the "-og" sound! Frog... log... bog... dog... Rhyming pairs are so fun to find! Poetry often uses rhyming words to sound musical!',
        points: 10,
      },
      {
        id: 'rhyming-4',
        type: 'multiple-choice',
        instruction: 'Which word RHYMES with "night"?',
        sentence: 'What has the same ending sound as "night"?',
        options: ['day', 'dark', 'light', 'moon'],
        correctAnswer: 'light',
        explanation: '🌙 Excellent! "Light" rhymes with "night" — they both end with the "-ight" sound! Night... light... bright... right... flight! There is a whole family of "-ight" words that all rhyme together!',
        points: 10,
      },
      {
        id: 'rhyming-5',
        type: 'multiple-choice',
        instruction: 'Which word does NOT rhyme with "bear"?',
        sentence: 'Three of these rhyme with "bear" — find the one that does NOT!',
        options: ['chair', 'hair', 'stair', 'cloud'],
        correctAnswer: 'cloud',
        explanation: '🐻 Superstar! "Cloud" does NOT rhyme with "bear"! Chair, hair, and stair all end with the "-air" sound like bear. "Cloud" has a completely different ending sound. You have a great ear for rhymes!',
        points: 10,
      },
    ],
  },
];

export function getTopicById(id: string): GrammarTopic | undefined {
  return GRAMMAR_TOPICS.find((topic) => topic.id === id);
}

export function isTopicUnlocked(topic: GrammarTopic, totalPoints: number): boolean {
  if (topic.requiredLevel === 0) return true;
  // Each level requires: Level 1 = 0pts, Level 2 = 100pts, Level 3 = 250pts etc.
  // We map requiredLevel to minPoints thresholds
  const levelThresholds: Record<number, number> = {
    1: 0,
    2: 100,
    3: 250,
    4: 500,
    5: 800,
  };
  const required = levelThresholds[topic.requiredLevel] ?? 0;
  return totalPoints >= required;
}
