import type { GrammarVideoData } from '@/types/grammarVideo';

export const GRAMMAR_VIDEOS: GrammarVideoData[] = [
  // ─── NOUNS ────────────────────────────────────────────────────────
  {
    topicId: 'nouns',
    title: 'What is a Noun?',
    frames: [
      {
        id: 'n1',
        duration: 3,
        background: 'from-blue-400 to-cyan-300',
        sceneEmoji: '🏷️',
        ambientEmojis: ['✨', '⭐', '💫'],
        caption: 'Today we are learning about NOUNS!',
        highlightWord: 'NOUNS',
        subCaption: 'Nouns are naming words',
      },
      {
        id: 'n2',
        duration: 3.5,
        background: 'from-green-400 to-emerald-300',
        sceneEmoji: '🐶',
        ambientEmojis: ['🌿', '🌸', '🍃'],
        caption: 'A noun can be an ANIMAL',
        highlightWord: 'ANIMAL',
        speechBubble: 'Woof! I am a dog!',
        exampleSentence: 'The dog ran fast.',
        exampleHighlight: 'dog',
      },
      {
        id: 'n3',
        duration: 3.5,
        background: 'from-orange-400 to-amber-300',
        sceneEmoji: '🏙️',
        ambientEmojis: ['🌟', '🏠', '🌆'],
        caption: 'A noun can be a PLACE',
        highlightWord: 'PLACE',
        speechBubble: 'I am a big city!',
        exampleSentence: 'We live in a city.',
        exampleHighlight: 'city',
      },
      {
        id: 'n4',
        duration: 3.5,
        background: 'from-purple-400 to-pink-300',
        sceneEmoji: '👩‍🏫',
        ambientEmojis: ['📚', '✏️', '🍎'],
        caption: 'A noun can be a PERSON',
        highlightWord: 'PERSON',
        speechBubble: 'Hello! I am your teacher!',
        exampleSentence: 'My teacher is kind.',
        exampleHighlight: 'teacher',
      },
      {
        id: 'n5',
        duration: 3.5,
        background: 'from-yellow-400 to-orange-300',
        sceneEmoji: '🍎',
        ambientEmojis: ['🍊', '🍇', '🍓'],
        caption: 'A noun can be a THING',
        highlightWord: 'THING',
        speechBubble: 'I am a yummy apple!',
        exampleSentence: 'She ate an apple.',
        exampleHighlight: 'apple',
      },
      {
        id: 'n6',
        duration: 4,
        background: 'from-blue-500 to-cyan-400',
        sceneEmoji: '🧠',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Remember: Nouns = People, Places, Animals, Things!',
        highlightWord: 'People, Places, Animals, Things',
        subCaption: 'If you can name it — it\'s a noun! 🏷️',
      },
    ],
  },

  // ─── VERBS ────────────────────────────────────────────────────────
  {
    topicId: 'verbs',
    title: 'What is a Verb?',
    frames: [
      {
        id: 'v1',
        duration: 3,
        background: 'from-yellow-400 to-orange-300',
        sceneEmoji: '⚡',
        ambientEmojis: ['💥', '✨', '🔥'],
        caption: 'Today we are learning about VERBS!',
        highlightWord: 'VERBS',
        subCaption: 'Verbs are action words!',
      },
      {
        id: 'v2',
        duration: 3.5,
        background: 'from-green-400 to-teal-300',
        sceneEmoji: '🐸',
        ambientEmojis: ['💦', '🌿', '🌊'],
        caption: 'A verb shows what someone DOES',
        highlightWord: 'DOES',
        speechBubble: 'I jump! I swim! I hop!',
        exampleSentence: 'The frog jumps over the log.',
        exampleHighlight: 'jumps',
      },
      {
        id: 'v3',
        duration: 3.5,
        background: 'from-sky-400 to-blue-300',
        sceneEmoji: '🐦',
        ambientEmojis: ['☁️', '🌤️', '⭐'],
        caption: 'Verbs describe the ACTION in a sentence',
        highlightWord: 'ACTION',
        speechBubble: 'Tweet! I sing all morning!',
        exampleSentence: 'Birds sing in the morning.',
        exampleHighlight: 'sing',
      },
      {
        id: 'v4',
        duration: 3.5,
        background: 'from-pink-400 to-rose-300',
        sceneEmoji: '📖',
        ambientEmojis: ['✨', '💫', '🌟'],
        caption: 'READING, RUNNING, EATING — all verbs!',
        highlightWord: 'READING, RUNNING, EATING',
        speechBubble: 'She reads every night!',
        exampleSentence: 'She reads every night.',
        exampleHighlight: 'reads',
      },
      {
        id: 'v5',
        duration: 3.5,
        background: 'from-purple-400 to-indigo-300',
        sceneEmoji: '🏃',
        ambientEmojis: ['💨', '⚡', '🌟'],
        caption: 'Ask "What is happening?" to find the verb!',
        highlightWord: 'What is happening',
        speechBubble: 'The boy RUNS fast!',
        exampleSentence: 'The boy runs very fast.',
        exampleHighlight: 'runs',
      },
      {
        id: 'v6',
        duration: 4,
        background: 'from-yellow-500 to-orange-400',
        sceneEmoji: '⚡',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Verbs = Action Words!',
        highlightWord: 'Action Words',
        subCaption: 'Jump, run, eat, sleep, play — these are all verbs! ⚡',
      },
    ],
  },

  // ─── ADJECTIVES ───────────────────────────────────────────────────
  {
    topicId: 'adjectives',
    title: 'What is an Adjective?',
    frames: [
      {
        id: 'a1',
        duration: 3,
        background: 'from-pink-400 to-rose-300',
        sceneEmoji: '🎨',
        ambientEmojis: ['🌈', '✨', '💫'],
        caption: 'Today we are learning about ADJECTIVES!',
        highlightWord: 'ADJECTIVES',
        subCaption: 'Adjectives are describing words!',
      },
      {
        id: 'a2',
        duration: 3.5,
        background: 'from-gray-500 to-slate-400',
        sceneEmoji: '🐘',
        ambientEmojis: ['🌿', '🌳', '🍃'],
        caption: 'Adjectives tell us MORE about a noun',
        highlightWord: 'MORE about a noun',
        speechBubble: 'I am a HUGE elephant!',
        exampleSentence: 'The huge elephant sat down.',
        exampleHighlight: 'huge',
      },
      {
        id: 'a3',
        duration: 3.5,
        background: 'from-yellow-400 to-amber-300',
        sceneEmoji: '🌟',
        ambientEmojis: ['✨', '💫', '⭐'],
        caption: 'Adjectives can describe how things LOOK',
        highlightWord: 'LOOK',
        speechBubble: 'Look at my sparkly dress!',
        exampleSentence: 'She wore a sparkly dress.',
        exampleHighlight: 'sparkly',
      },
      {
        id: 'a4',
        duration: 3.5,
        background: 'from-orange-400 to-red-300',
        sceneEmoji: '🏠',
        ambientEmojis: ['🕯️', '☕', '🧸'],
        caption: 'Adjectives can describe how things FEEL',
        highlightWord: 'FEEL',
        speechBubble: 'Our home is so cozy!',
        exampleSentence: 'We live in a cozy house.',
        exampleHighlight: 'cozy',
      },
      {
        id: 'a5',
        duration: 3.5,
        background: 'from-green-400 to-teal-300',
        sceneEmoji: '🐁',
        ambientEmojis: ['🌿', '🍃', '🌱'],
        caption: 'Adjectives can describe SIZE, COLOUR and more!',
        highlightWord: 'SIZE, COLOUR',
        speechBubble: 'I\'m a tiny grey mouse!',
        exampleSentence: 'The tiny mouse hid under the bed.',
        exampleHighlight: 'tiny',
      },
      {
        id: 'a6',
        duration: 4,
        background: 'from-pink-500 to-rose-400',
        sceneEmoji: '🎨',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Adjectives = Describing Words!',
        highlightWord: 'Describing Words',
        subCaption: 'Big, small, red, happy, soft — these are adjectives! 🎨',
      },
    ],
  },

  // ─── PRONOUNS ─────────────────────────────────────────────────────
  {
    topicId: 'pronouns',
    title: 'What is a Pronoun?',
    frames: [
      {
        id: 'pr1',
        duration: 3,
        background: 'from-purple-400 to-violet-300',
        sceneEmoji: '🔄',
        ambientEmojis: ['✨', '💫', '🌀'],
        caption: 'Today we are learning about PRONOUNS!',
        highlightWord: 'PRONOUNS',
        subCaption: 'Pronouns replace nouns so we don\'t repeat ourselves!',
      },
      {
        id: 'pr2',
        duration: 4,
        background: 'from-blue-400 to-indigo-300',
        sceneEmoji: '👦',
        ambientEmojis: ['⭐', '🎈', '🌟'],
        caption: 'Instead of saying a name again, we use a pronoun!',
        highlightWord: 'pronoun',
        speechBubble: 'I am Jake! You can call me HE!',
        exampleSentence: 'Jake is kind. He loves to read.',
        exampleHighlight: 'He',
      },
      {
        id: 'pr3',
        duration: 3.5,
        background: 'from-pink-400 to-fuchsia-300',
        sceneEmoji: '👧',
        ambientEmojis: ['🌸', '🌺', '💐'],
        caption: 'SHE replaces a girl\'s name',
        highlightWord: 'SHE',
        speechBubble: 'She loves to dance!',
        exampleSentence: 'Mia dances well. She is graceful.',
        exampleHighlight: 'She',
      },
      {
        id: 'pr4',
        duration: 3.5,
        background: 'from-green-400 to-emerald-300',
        sceneEmoji: '👨‍👩‍👧‍👦',
        ambientEmojis: ['🏡', '🌳', '☀️'],
        caption: 'THEY replaces a group of people',
        highlightWord: 'THEY',
        speechBubble: 'They played in the park!',
        exampleSentence: 'The children played. They had fun.',
        exampleHighlight: 'They',
      },
      {
        id: 'pr5',
        duration: 3.5,
        background: 'from-amber-400 to-yellow-300',
        sceneEmoji: '🐱',
        ambientEmojis: ['🌙', '⭐', '🌟'],
        caption: 'IT replaces a thing or animal',
        highlightWord: 'IT',
        speechBubble: 'It is a fluffy cat!',
        exampleSentence: 'The cat sleeps. It is so fluffy.',
        exampleHighlight: 'It',
      },
      {
        id: 'pr6',
        duration: 4,
        background: 'from-purple-500 to-violet-400',
        sceneEmoji: '🔄',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'I • You • He • She • It • We • They',
        highlightWord: 'I • You • He • She • It • We • They',
        subCaption: 'These are all pronouns! They replace nouns. 🔄',
      },
    ],
  },

  // ─── ADVERBS ──────────────────────────────────────────────────────
  {
    topicId: 'adverbs',
    title: 'What is an Adverb?',
    frames: [
      {
        id: 'ad1',
        duration: 3,
        background: 'from-teal-400 to-green-300',
        sceneEmoji: '🌊',
        ambientEmojis: ['💨', '🌀', '✨'],
        caption: 'Today we are learning about ADVERBS!',
        highlightWord: 'ADVERBS',
        subCaption: 'Adverbs tell us more about verbs!',
      },
      {
        id: 'ad2',
        duration: 3.5,
        background: 'from-orange-400 to-amber-300',
        sceneEmoji: '🐢',
        ambientEmojis: ['🍃', '🌿', '🌱'],
        caption: 'Adverbs tell us HOW something happens',
        highlightWord: 'HOW',
        speechBubble: 'I walk very slowly...',
        exampleSentence: 'The turtle walked slowly.',
        exampleHighlight: 'slowly',
      },
      {
        id: 'ad3',
        duration: 3.5,
        background: 'from-blue-400 to-sky-300',
        sceneEmoji: '🪥',
        ambientEmojis: ['💧', '✨', '⭐'],
        caption: 'Adverbs tell us WHEN something happens',
        highlightWord: 'WHEN',
        speechBubble: 'I always brush my teeth!',
        exampleSentence: 'She always brushes her teeth.',
        exampleHighlight: 'always',
      },
      {
        id: 'ad4',
        duration: 3.5,
        background: 'from-pink-400 to-rose-300',
        sceneEmoji: '🐰',
        ambientEmojis: ['💨', '⚡', '🌟'],
        caption: 'Adverbs tell us WHERE something happens',
        highlightWord: 'WHERE',
        speechBubble: 'I ran away as fast as I could!',
        exampleSentence: 'The rabbit ran away quickly.',
        exampleHighlight: 'away',
      },
      {
        id: 'ad5',
        duration: 3.5,
        background: 'from-indigo-400 to-purple-300',
        sceneEmoji: '🔊',
        ambientEmojis: ['🎵', '🎶', '🎸'],
        caption: 'Many adverbs end in -LY!',
        highlightWord: '-LY',
        speechBubble: 'She sang LOUDLY on stage!',
        exampleSentence: 'She sang loudly and happily.',
        exampleHighlight: 'loudly',
      },
      {
        id: 'ad6',
        duration: 4,
        background: 'from-teal-500 to-green-400',
        sceneEmoji: '🌊',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Adverbs = How, When, Where words!',
        highlightWord: 'How, When, Where',
        subCaption: 'Slowly, always, loudly, here — these are adverbs! 🌊',
      },
    ],
  },

  // ─── PUNCTUATION ──────────────────────────────────────────────────
  {
    topicId: 'punctuation',
    title: 'Punctuation Marks!',
    frames: [
      {
        id: 'pu1',
        duration: 3,
        background: 'from-red-400 to-pink-300',
        sceneEmoji: '📍',
        ambientEmojis: ['❓', '❗', '💬'],
        caption: 'Today we are learning about PUNCTUATION!',
        highlightWord: 'PUNCTUATION',
        subCaption: 'Punctuation marks help us read and understand sentences!',
      },
      {
        id: 'pu2',
        duration: 3.5,
        background: 'from-blue-400 to-indigo-300',
        sceneEmoji: '🔵',
        ambientEmojis: ['✏️', '📝', '📄'],
        caption: 'A FULL STOP (.) ends a sentence',
        highlightWord: 'FULL STOP (.)',
        speechBubble: 'I love ice cream.',
        exampleSentence: 'I love ice cream.',
        exampleHighlight: '.',
        subCaption: 'Use it when you are making a statement.',
      },
      {
        id: 'pu3',
        duration: 3.5,
        background: 'from-yellow-400 to-amber-300',
        sceneEmoji: '❓',
        ambientEmojis: ['🤔', '💭', '🌟'],
        caption: 'A QUESTION MARK (?) asks something',
        highlightWord: 'QUESTION MARK (?)',
        speechBubble: 'What is your name?',
        exampleSentence: 'What is your name?',
        exampleHighlight: '?',
        subCaption: 'Use it when you are asking a question!',
      },
      {
        id: 'pu4',
        duration: 3.5,
        background: 'from-orange-400 to-red-300',
        sceneEmoji: '❗',
        ambientEmojis: ['🎉', '🎊', '💥'],
        caption: 'An EXCLAMATION MARK (!) shows excitement!',
        highlightWord: 'EXCLAMATION MARK (!)',
        speechBubble: 'That was AMAZING!',
        exampleSentence: 'That was amazing!',
        exampleHighlight: '!',
        subCaption: 'Use it when something is exciting or surprising!',
      },
      {
        id: 'pu5',
        duration: 3.5,
        background: 'from-green-400 to-teal-300',
        sceneEmoji: '✏️',
        ambientEmojis: ['📚', '📖', '🎓'],
        caption: 'Every sentence needs punctuation at the END',
        highlightWord: 'END',
        speechBubble: 'Always end your sentence properly!',
        exampleSentence: 'The cat is cute.',
        exampleHighlight: '.',
      },
      {
        id: 'pu6',
        duration: 4,
        background: 'from-red-500 to-pink-400',
        sceneEmoji: '📍',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: '. for statements • ? for questions • ! for excitement',
        highlightWord: '. • ? • !',
        subCaption: 'These tiny marks make a BIG difference! 📍',
      },
    ],
  },

  // ─── SENTENCES ────────────────────────────────────────────────────
  {
    topicId: 'sentences',
    title: 'Building Sentences!',
    frames: [
      {
        id: 'se1',
        duration: 3,
        background: 'from-indigo-400 to-blue-300',
        sceneEmoji: '🔨',
        ambientEmojis: ['🧱', '⚙️', '✨'],
        caption: 'Today we are learning about SENTENCES!',
        highlightWord: 'SENTENCES',
        subCaption: 'A sentence is a complete thought!',
      },
      {
        id: 'se2',
        duration: 3.5,
        background: 'from-purple-400 to-pink-300',
        sceneEmoji: '👤',
        ambientEmojis: ['⭐', '💡', '🌟'],
        caption: 'Every sentence has a SUBJECT (who or what)',
        highlightWord: 'SUBJECT',
        speechBubble: 'I am the subject — I do the action!',
        exampleSentence: 'The dog ran fast.',
        exampleHighlight: 'The dog',
      },
      {
        id: 'se3',
        duration: 3.5,
        background: 'from-green-400 to-teal-300',
        sceneEmoji: '⚡',
        ambientEmojis: ['💨', '🏃', '✨'],
        caption: 'Every sentence has a PREDICATE (what happens)',
        highlightWord: 'PREDICATE',
        speechBubble: 'I tell you what happens!',
        exampleSentence: 'The dog ran fast.',
        exampleHighlight: 'ran fast',
      },
      {
        id: 'se4',
        duration: 3.5,
        background: 'from-amber-400 to-yellow-300',
        sceneEmoji: '🔤',
        ambientEmojis: ['✏️', '📝', '🌟'],
        caption: 'Sentences start with a CAPITAL LETTER',
        highlightWord: 'CAPITAL LETTER',
        speechBubble: 'Always start big — like me, T!',
        exampleSentence: 'The sun shines brightly.',
        exampleHighlight: 'T',
      },
      {
        id: 'se5',
        duration: 3.5,
        background: 'from-rose-400 to-red-300',
        sceneEmoji: '✅',
        ambientEmojis: ['🎉', '⭐', '🌈'],
        caption: 'A complete sentence makes FULL SENSE',
        highlightWord: 'FULL SENSE',
        speechBubble: 'Subject + Predicate = Complete sentence!',
        exampleSentence: 'She loves chocolate cake.',
        exampleHighlight: 'She loves chocolate cake',
      },
      {
        id: 'se6',
        duration: 4,
        background: 'from-indigo-500 to-blue-400',
        sceneEmoji: '🔨',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Capital letter + Subject + Predicate + Punctuation!',
        highlightWord: 'Capital letter + Subject + Predicate + Punctuation',
        subCaption: 'Put them together and you have a perfect sentence! 🔨',
      },
    ],
  },

  // ─── RHYMING ──────────────────────────────────────────────────────
  {
    topicId: 'rhyming',
    title: 'Rhyming Words!',
    frames: [
      {
        id: 'rh1',
        duration: 3,
        background: 'from-amber-400 to-yellow-300',
        sceneEmoji: '🎵',
        ambientEmojis: ['🎶', '🎸', '🎤'],
        caption: 'Today we are learning about RHYMING WORDS!',
        highlightWord: 'RHYMING WORDS',
        subCaption: 'Rhyming words sound the same at the end!',
      },
      {
        id: 'rh2',
        duration: 3.5,
        background: 'from-pink-400 to-rose-300',
        sceneEmoji: '🐱',
        ambientEmojis: ['🎩', '🏏', '🪑'],
        caption: 'CAT rhymes with HAT, BAT and MAT!',
        highlightWord: 'CAT • HAT • BAT • MAT',
        speechBubble: 'Cat... hat... bat... mat! 🎵',
        exampleSentence: 'The cat sat on a mat.',
        exampleHighlight: 'cat',
      },
      {
        id: 'rh3',
        duration: 3.5,
        background: 'from-blue-400 to-sky-300',
        sceneEmoji: '🌳',
        ambientEmojis: ['🐝', '🌿', '🌸'],
        caption: 'TREE rhymes with BEE, SEE and FREE!',
        highlightWord: 'TREE • BEE • SEE • FREE',
        speechBubble: 'Tree... bee... see... free! 🎵',
        exampleSentence: 'A bee sat on a tree.',
        exampleHighlight: 'bee',
      },
      {
        id: 'rh4',
        duration: 3.5,
        background: 'from-indigo-400 to-purple-300',
        sceneEmoji: '🌙',
        ambientEmojis: ['⭐', '✨', '🌟'],
        caption: 'MOON rhymes with SPOON, TUNE and SOON!',
        highlightWord: 'MOON • SPOON • TUNE • SOON',
        speechBubble: 'Moon... spoon... tune... soon! 🎵',
        exampleSentence: 'I see the moon very soon.',
        exampleHighlight: 'moon',
      },
      {
        id: 'rh5',
        duration: 3.5,
        background: 'from-green-400 to-emerald-300',
        sceneEmoji: '🎤',
        ambientEmojis: ['🎵', '🎶', '✨'],
        caption: 'Listen to the ENDING sound to find rhymes!',
        highlightWord: 'ENDING sound',
        speechBubble: 'Star... car... far... jar! They all end in -AR!',
        exampleSentence: 'A star fell from far away.',
        exampleHighlight: 'star',
      },
      {
        id: 'rh6',
        duration: 4,
        background: 'from-amber-500 to-yellow-400',
        sceneEmoji: '🎵',
        ambientEmojis: ['💡', '⭐', '🌈'],
        caption: 'Rhyming makes reading fun and helps you remember words!',
        highlightWord: 'fun',
        subCaption: 'Poems, songs and stories love rhyming words! 🎵',
      },
    ],
  },
];

export function getVideoForTopic(topicId: string): GrammarVideoData | undefined {
  return GRAMMAR_VIDEOS.find((v) => v.topicId === topicId);
}
