import type { Story } from '@/types';

export const STORIES: Story[] = [
  {
    id: 'three-little-pigs',
    title: 'The Three Little Pigs',
    coverEmoji: '🐷',
    coverGradient: 'from-pink-400 to-orange-300',
    tagline: 'Build smart, stay safe!',
    ageRange: '4-7',
    readingTime: '5 min',
    difficulty: 'beginner',
    category: 'Classic Tales',
    moral: 'Hard work and planning keep us safe',
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 's1-p1',
        title: 'The Three Brothers',
        text: 'Once upon a time, three little pig brothers lived with their mother in a cozy home. One sunny day, their mother said it was time for them to go out into the world and build their own houses. She hugged each one tightly and said, "Work hard and be careful, my darlings!" The three little pigs set off down the road, singing and laughing together.',
        scene: {
          background: 'from-green-300 to-emerald-200',
          foregroundEmojis: '🌳🏡🌳',
          characterLeft: '🐷',
          characterRight: '🐷',
          ambientEmojis: ['☀️', '🌸', '🦋', '🌿'],
        },
      },
      {
        id: 's1-p2',
        title: 'The Straw House',
        text: 'The first little pig was very lazy. He saw some bundles of straw on the road and thought, "This will be easy to build with!" He quickly threw together a little house made of straw. It was done in just one afternoon! "Now I can play all day!" he said happily, dancing around his wobbly house.',
        scene: {
          background: 'from-yellow-300 to-amber-200',
          foregroundEmojis: '🌾🏠🌾',
          characterLeft: '🐷',
          characterRight: '🐺',
          ambientEmojis: ['🌻', '☀️', '🦗', '🍂'],
        },
      },
      {
        id: 's1-p3',
        title: 'The Stick House',
        text: 'The second little pig was a little less lazy. He found some sticks in the forest and built a house with them. It took a whole day to build, and when it was done, he smiled proudly. "This is good enough!" he said. His stick house was stronger than his brother\'s straw house, but still not very sturdy.',
        scene: {
          background: 'from-amber-300 to-orange-200',
          foregroundEmojis: '🌲🏠🌲',
          characterLeft: '🐷',
          characterRight: '🌲',
          ambientEmojis: ['🍁', '🌿', '🐦', '🍃'],
        },
      },
      {
        id: 's1-p4',
        title: 'The Brick House',
        text: 'The third little pig was very hard-working. He chose strong, heavy bricks for his house. He worked for many days, placing each brick carefully. When his brothers came to play, he said, "I must finish my house first!" Finally, his beautiful brick house was complete. It had a strong door, real windows, and a proper chimney.',
        scene: {
          background: 'from-orange-300 to-red-200',
          foregroundEmojis: '🧱🏠🧱',
          characterLeft: '🐷',
          characterRight: '🔨',
          ambientEmojis: ['⭐', '💪', '🌟', '✨'],
        },
      },
      {
        id: 's1-p5',
        title: 'The Big Bad Wolf',
        text: 'Then one day, the Big Bad Wolf came! He huffed and puffed and blew down the straw house! The first pig ran to his brother\'s stick house. The wolf huffed and puffed again and blew that down too! Both pigs ran to the brick house. The wolf tried and tried, but no matter how hard he huffed and puffed, the brick house stood firm. Finally, the tired wolf ran away, and the three little pigs were safe forever in the strong brick house!',
        scene: {
          background: 'from-red-400 to-orange-300',
          foregroundEmojis: '🧱🏰🧱',
          characterLeft: '🐺',
          characterRight: '🐷',
          ambientEmojis: ['💨', '🌪️', '⭐', '🎉'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q1-pigs-1',
        afterSegmentId: 's1-p2',
        question: 'What did the first little pig use to build his house?',
        options: ['Bricks', 'Straw', 'Sticks'],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '🎉 Brilliant! You remembered perfectly! The first pig used straw!',
        feedbackWrong: 'Hmm, not quite! Let me help you remember...',
        reminderText: 'The first little pig saw straw on the road and used it to quickly build his house in just one afternoon!',
        reminderSegmentId: 's1-p2',
      },
      {
        id: 'q1-pigs-2',
        afterSegmentId: 's1-p4',
        question: 'Which pig worked the hardest to build the strongest house?',
        options: ['The first pig', 'The second pig', 'The third pig'],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: '⭐ Amazing memory! The third pig worked for many days to build the strong brick house!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'The third pig was very hard-working and chose heavy bricks. He worked for many days to build a strong house while his brothers played!',
        reminderSegmentId: 's1-p4',
      },
    ],
  },
  {
    id: 'goldilocks',
    title: 'Goldilocks and the Three Bears',
    coverEmoji: '🐻',
    coverGradient: 'from-yellow-300 to-amber-400',
    tagline: 'Just right makes everything nice!',
    ageRange: '4-7',
    readingTime: '5 min',
    difficulty: 'beginner',
    category: 'Classic Tales',
    moral: "Always respect other people's belongings",
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 's2-g1',
        title: 'The Bears Go Walking',
        text: 'Deep in the forest lived three bears — Papa Bear, Mama Bear, and Baby Bear. One morning, Mama Bear made three bowls of porridge for breakfast. But the porridge was too hot to eat! So the three bears went for a walk in the forest to wait for it to cool down. They had no idea that a curious little girl with golden hair was about to visit their house!',
        scene: {
          background: 'from-green-400 to-teal-300',
          foregroundEmojis: '🌲🏡🌲',
          characterLeft: '🐻',
          characterRight: '🐻',
          ambientEmojis: ['🌿', '🌸', '🦌', '☀️'],
        },
      },
      {
        id: 's2-g2',
        title: 'Goldilocks Tries the Porridge',
        text: 'Goldilocks skipped through the forest and found the bears\' little cottage. She knocked on the door — nobody answered! So she peeked inside and walked in. On the table were three bowls of porridge. She tried the big bowl first: "Too hot!" She tried the medium bowl: "Too cold!" Then she tried the tiny bowl: "Mmm, just right!" And she ate it all up!',
        scene: {
          background: 'from-yellow-300 to-orange-200',
          foregroundEmojis: '🥣🍲🥣',
          characterLeft: '👧',
          characterRight: '🥄',
          ambientEmojis: ['✨', '🌟', '💛', '🍯'],
        },
      },
      {
        id: 's2-g3',
        title: 'Goldilocks Tries the Chairs',
        text: 'After eating, Goldilocks saw three chairs. She tried the big chair: "Too hard!" She tried the medium chair: "Too soft!" Then she tried the tiny chair: "Just right!" She sat down happily — but oh no! She was too heavy for Baby Bear\'s little chair, and CRACK! It broke into pieces! Goldilocks felt very sorry.',
        scene: {
          background: 'from-amber-300 to-yellow-200',
          foregroundEmojis: '🪑💺🪑',
          characterLeft: '👧',
          characterRight: '💥',
          ambientEmojis: ['😬', '🌟', '💫', '✨'],
        },
      },
      {
        id: 's2-g4',
        title: 'Goldilocks Finds the Beds',
        text: 'Goldilocks was tired from all her exploring, so she went upstairs. She tried Papa Bear\'s big bed: "Too hard!" She tried Mama Bear\'s medium bed: "Too soft!" Then she tried Baby Bear\'s little bed: "Just right!" She snuggled down under the covers and fell fast asleep, dreaming of honey and flowers.',
        scene: {
          background: 'from-purple-300 to-pink-200',
          foregroundEmojis: '🛏️😴🌙',
          characterLeft: '👧',
          characterRight: '⭐',
          ambientEmojis: ['💤', '🌙', '⭐', '✨'],
        },
      },
      {
        id: 's2-g5',
        title: 'The Bears Come Home!',
        text: 'The three bears came home from their walk. "Someone\'s been eating my porridge!" roared Papa Bear. "Someone\'s been eating MY porridge!" said Mama Bear. "Someone\'s been eating my porridge and ate it ALL UP!" cried Baby Bear. They found the broken chair and then went upstairs. Goldilocks woke up, saw three bears staring at her, jumped out of bed, ran out of the house, and never came back! And she always knocked and waited for an answer after that.',
        scene: {
          background: 'from-orange-400 to-red-300',
          foregroundEmojis: '🐻🐻🐻',
          characterLeft: '👧',
          characterRight: '🐻',
          ambientEmojis: ['😱', '💨', '🌟', '🏃'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q2-gold-1',
        afterSegmentId: 's2-g2',
        question: 'Which bowl of porridge was "just right" for Goldilocks?',
        options: ["Papa Bear's big bowl", "Mama Bear's medium bowl", "Baby Bear's tiny bowl"],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: '🎉 You got it! Baby Bear\'s tiny bowl was just right for Goldilocks!',
        feedbackWrong: "Hmm, let me help you remember...",
        reminderText: "Goldilocks tried all three bowls! Papa Bear's was too hot, Mama Bear's was too cold, and Baby Bear's tiny bowl was just right!",
        reminderSegmentId: 's2-g2',
      },
      {
        id: 'q2-gold-2',
        afterSegmentId: 's2-g4',
        question: "Which bed did Goldilocks sleep in?",
        options: ["Papa Bear's big bed", "Mama Bear's medium bed", "Baby Bear's little bed"],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: "⭐ Wonderful! Baby Bear's little bed was just right for sleeping!",
        feedbackWrong: "Oops! Let me help you remember...",
        reminderText: "Goldilocks tried all three beds! Papa Bear's was too hard, Mama Bear's was too soft, but Baby Bear's little bed was just right — and she fell fast asleep!",
        reminderSegmentId: 's2-g4',
      },
    ],
  },
  {
    id: 'jack-beanstalk',
    title: 'Jack and the Beanstalk',
    coverEmoji: '🌱',
    coverGradient: 'from-green-400 to-emerald-300',
    tagline: 'Dare to climb to the sky!',
    ageRange: '6-10',
    readingTime: '7 min',
    difficulty: 'explorer',
    category: 'Adventure Tales',
    moral: 'Courage and cleverness can overcome great challenges',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 's3-j1',
        title: 'The Magic Beans',
        text: 'Jack and his mother were very poor. Their only treasure was their old cow, Bessie. One day, their mother said they must sell the cow to buy food. On the way to market, Jack met a mysterious old man who offered five magic beans for the cow. Jack made the trade! But when he got home, his mother was so angry that she threw the beans out the window.',
        scene: {
          background: 'from-amber-300 to-yellow-200',
          foregroundEmojis: '🌾🏚️🐄',
          characterLeft: '👦',
          characterRight: '🧓',
          ambientEmojis: ['✨', '💚', '🌟', '🪄'],
        },
      },
      {
        id: 's3-j2',
        title: 'The Giant Beanstalk',
        text: 'The next morning, Jack woke up and couldn\'t believe his eyes! The magic beans had grown into an enormous beanstalk that reached all the way up through the clouds! It was so tall Jack couldn\'t see the top. "I must find out where it goes!" said brave Jack. He grabbed hold of the beanstalk and started climbing, higher and higher and higher!',
        scene: {
          background: 'from-green-400 to-emerald-300',
          foregroundEmojis: '🌱🌿🌳',
          characterLeft: '👦',
          characterRight: '☁️',
          ambientEmojis: ['☁️', '🌤️', '⭐', '🌿'],
        },
      },
      {
        id: 's3-j3',
        title: 'The Giant\'s Castle',
        text: 'At the top of the beanstalk, Jack found a magical land in the clouds! In the distance stood an enormous castle. A kind giantess opened the door and warned Jack that her husband, the terrifying giant, ate boys for breakfast! She hid Jack in the oven just as the giant stomped in, shaking the whole castle. "FEE FI FO FUM!" roared the giant, sniffing the air.',
        scene: {
          background: 'from-purple-400 to-blue-300',
          foregroundEmojis: '☁️🏰☁️',
          characterLeft: '👦',
          characterRight: '👹',
          ambientEmojis: ['☁️', '⭐', '💜', '🌙'],
        },
      },
      {
        id: 's3-j4',
        title: 'The Golden Treasures',
        text: 'The giant counted his bags of gold coins, then fell asleep snoring loudly. Jack crept out and grabbed a bag of gold! He ran to the beanstalk and slid down. His mother was overjoyed! The gold kept them comfortable for a while, but Jack climbed the beanstalk two more times — once to get a magical hen that laid golden eggs, and once to get a golden harp that played music by itself!',
        scene: {
          background: 'from-yellow-400 to-amber-300',
          foregroundEmojis: '🥚🪙🎵',
          characterLeft: '👦',
          characterRight: '🐔',
          ambientEmojis: ['✨', '💛', '⭐', '🌟'],
        },
      },
      {
        id: 's3-j5',
        title: 'The Giant Falls',
        text: 'On his last trip, the giant woke up and chased Jack down the beanstalk! "Help! Mother, bring the axe!" Jack shouted as he scrambled down. His mother threw him the axe and Jack chopped at the beanstalk with all his might. CRASH! Down came the beanstalk and the giant fell away into the clouds, never to be seen again. Jack, his mother, and the magical hen lived happily ever after with plenty of golden eggs!',
        scene: {
          background: 'from-blue-400 to-cyan-300',
          foregroundEmojis: '🌱⚡🏠',
          characterLeft: '👦',
          characterRight: '🪓',
          ambientEmojis: ['🎉', '⭐', '💫', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q3-jack-1',
        afterSegmentId: 's3-j1',
        question: 'What did Jack trade his cow for?',
        options: ['A bag of gold', 'Five magic beans', 'A golden harp'],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 You remembered! Jack traded the cow for five magic beans from a mysterious old man!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'A mysterious old man offered Jack five magic beans in exchange for his cow Bessie. His mother was very angry when Jack came home!',
        reminderSegmentId: 's3-j1',
      },
      {
        id: 'q3-jack-2',
        afterSegmentId: 's3-j4',
        question: 'What magical creature did Jack find in the giant\'s castle that laid golden eggs?',
        options: ['A golden goose', 'A magic hen', 'A rainbow parrot'],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '⭐ Excellent! It was a magical hen that could lay golden eggs!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'In the giant\'s castle, Jack found a magical hen that laid golden eggs! He also found gold coins and a golden harp that played music by itself.',
        reminderSegmentId: 's3-j4',
      },
    ],
  },
  {
    id: 'clever-crow',
    title: 'The Clever Crow',
    coverEmoji: '🦅',
    coverGradient: 'from-blue-400 to-cyan-300',
    tagline: 'Think smart, never give up!',
    ageRange: '5-9',
    readingTime: '4 min',
    difficulty: 'explorer',
    category: 'Wisdom Tales',
    moral: 'Intelligence and patience solve problems',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 's4-c1',
        title: 'A Very Thirsty Crow',
        text: 'On a scorching hot summer day, a clever crow was flying over the fields, desperately searching for water. The sun blazed down and the crow\'s throat was parched and dry. "Water, water, I must find water!" the crow croaked. After searching for a long time, the tired crow finally spotted a tall clay pot sitting in a garden. With hope in his heart, he fluttered down to look inside.',
        scene: {
          background: 'from-orange-400 to-yellow-300',
          foregroundEmojis: '☀️🌿☀️',
          characterLeft: '🦅',
          characterRight: '🏺',
          ambientEmojis: ['☀️', '🌡️', '💦', '🌬️'],
        },
      },
      {
        id: 's4-c2',
        title: 'The Water is Too Low',
        text: 'The crow peeked into the pot and could see water at the bottom — but it was too low for his beak to reach! He tried tilting the pot but it was too heavy. He tried reaching in but his beak was too short. He tried and tried but couldn\'t get a single drop. The crow felt very discouraged. But then he had a wonderful, brilliant idea! He looked around the garden with his sharp, clever eyes.',
        scene: {
          background: 'from-blue-300 to-cyan-200',
          foregroundEmojis: '🏺💧🏺',
          characterLeft: '🦅',
          characterRight: '💭',
          ambientEmojis: ['💡', '💧', '🔵', '✨'],
        },
      },
      {
        id: 's4-c3',
        title: 'The Crow\'s Brilliant Plan',
        text: 'The clever crow spotted small pebbles and stones scattered all around the garden. "Aha!" he cried. One by one, the crow picked up each pebble in his beak and carefully dropped it into the pot. PLOP! PLOP! PLOP! With each pebble that went in, the water rose up just a little bit higher. The crow worked patiently, not giving up even when his wings were tired. Drop by drop, the water was rising!',
        scene: {
          background: 'from-teal-400 to-green-300',
          foregroundEmojis: '🪨💧🪨',
          characterLeft: '🦅',
          characterRight: '🏺',
          ambientEmojis: ['💪', '⭐', '💧', '✨'],
        },
      },
      {
        id: 's4-c4',
        title: 'Sweet Success!',
        text: 'After dropping in many, many pebbles, the water finally rose high enough to reach the crow\'s beak! The crow dipped his beak into the cool, refreshing water and drank deeply. "Ahhhh!" he sighed with joy. Other animals in the garden had been watching in amazement. "How clever!" said a rabbit. "How patient!" said a squirrel. The crow had solved a difficult problem by thinking carefully and never giving up. And from that day on, all the animals called him the Cleverest Crow in the land!',
        scene: {
          background: 'from-cyan-400 to-blue-300',
          foregroundEmojis: '🏺💧🎉',
          characterLeft: '🦅',
          characterRight: '🐰',
          ambientEmojis: ['🎉', '⭐', '💫', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q4-crow-1',
        afterSegmentId: 's4-c2',
        question: 'Why couldn\'t the crow drink the water at first?',
        options: [
          'The water was too dirty',
          'The water was too low in the pot',
          'The pot was empty',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 Brilliant! The water was too low for the crow\'s beak to reach!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'The crow could SEE water in the pot, but it was at the bottom — too low for his beak to reach! He tried tilting the heavy pot but couldn\'t manage it.',
        reminderSegmentId: 's4-c2',
      },
      {
        id: 'q4-crow-2',
        afterSegmentId: 's4-c3',
        question: 'What clever idea did the crow use to raise the water level?',
        options: [
          'He poured more water from a stream',
          'He used a long stick to lift the pot',
          'He dropped pebbles into the pot one by one',
        ],
        correctIndex: 2,
        points: 25,
        feedbackCorrect: '⭐ Perfect! The crow dropped pebbles in one by one to raise the water level — so smart!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'The clever crow spotted pebbles in the garden and had a brilliant idea! He dropped them one by one into the pot. PLOP! PLOP! PLOP! Each pebble made the water rise a little higher!',
        reminderSegmentId: 's4-c3',
      },
    ],
  },
];

export function getStoryById(id: string): Story | undefined {
  return STORIES.find((s) => s.id === id);
}
