import type { Story } from '@/types';

export const STORIES: Story[] = [
  {
    id: 'three-little-pigs',
    title: 'The Three Little Pigs',
    coverEmoji: '🐷',
    coverGradient: 'from-pink-400 to-orange-300',
    tagline: 'Build smart, stay safe!',
    ageRange: '4-7',
    readingTime: '5 min',
    difficulty: 'beginner',
    category: 'Classic Tales',
    moral: 'Hard work and planning keep us safe',
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 's1-p1',
        title: 'The Three Brothers',
        text: 'Once upon a time, three little pig brothers lived with their mother in a cozy home. One sunny day, their mother said it was time for them to go out into the world and build their own houses. She hugged each one tightly and said, "Work hard and be careful, my darlings!" The three little pigs set off down the road, singing and laughing together.',
        scene: {
          background: 'from-green-300 to-emerald-200',
          foregroundEmojis: '🌳🏡🌳',
          characterLeft: '🐷',
          characterRight: '🐷',
          ambientEmojis: ['☀️', '🌸', '🦋', '🌿'],
        },
      },
      {
        id: 's1-p2',
        title: 'The Straw House',
        text: 'The first little pig was very lazy. He saw some bundles of straw on the road and thought, "This will be easy to build with!" He quickly threw together a little house made of straw. It was done in just one afternoon! "Now I can play all day!" he said happily, dancing around his wobbly house.',
        scene: {
          background: 'from-yellow-300 to-amber-200',
          foregroundEmojis: '🌾🏠🌾',
          characterLeft: '🐷',
          characterRight: '🐺',
          ambientEmojis: ['🌻', '☀️', '🦗', '🍂'],
        },
      },
      {
        id: 's1-p3',
        title: 'The Stick House',
        text: 'The second little pig was a little less lazy. He found some sticks in the forest and built a house with them. It took a whole day to build, and when it was done, he smiled proudly. "This is good enough!" he said. His stick house was stronger than his brother\'s straw house, but still not very sturdy.',
        scene: {
          background: 'from-amber-300 to-orange-200',
          foregroundEmojis: '🌲🏠🌲',
          characterLeft: '🐷',
          characterRight: '🌲',
          ambientEmojis: ['🍁', '🌿', '🐦', '🍃'],
        },
      },
      {
        id: 's1-p4',
        title: 'The Brick House',
        text: 'The third little pig was very hard-working. He chose strong, heavy bricks for his house. He worked for many days, placing each brick carefully. When his brothers came to play, he said, "I must finish my house first!" Finally, his beautiful brick house was complete. It had a strong door, real windows, and a proper chimney.',
        scene: {
          background: 'from-orange-300 to-red-200',
          foregroundEmojis: '🧱🏠🧱',
          characterLeft: '🐷',
          characterRight: '🔨',
          ambientEmojis: ['⭐', '💪', '🌟', '✨'],
        },
      },
      {
        id: 's1-p5',
        title: 'The Big Bad Wolf',
        text: 'Then one day, the Big Bad Wolf came! He huffed and puffed and blew down the straw house! The first pig ran to his brother\'s stick house. The wolf huffed and puffed again and blew that down too! Both pigs ran to the brick house. The wolf tried and tried, but no matter how hard he huffed and puffed, the brick house stood firm. Finally, the tired wolf ran away, and the three little pigs were safe forever in the strong brick house!',
        scene: {
          background: 'from-red-400 to-orange-300',
          foregroundEmojis: '🧱🏰🧱',
          characterLeft: '🐺',
          characterRight: '🐷',
          ambientEmojis: ['💨', '🌪️', '⭐', '🎉'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q1-pigs-1',
        afterSegmentId: 's1-p2',
        question: 'What did the first little pig use to build his house?',
        options: ['Bricks', 'Straw', 'Sticks'],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '🎉 Brilliant! You remembered perfectly! The first pig used straw!',
        feedbackWrong: 'Hmm, not quite! Let me help you remember...',
        reminderText: 'The first little pig saw straw on the road and used it to quickly build his house in just one afternoon!',
        reminderSegmentId: 's1-p2',
      },
      {
        id: 'q1-pigs-2',
        afterSegmentId: 's1-p4',
        question: 'Which pig worked the hardest to build the strongest house?',
        options: ['The first pig', 'The second pig', 'The third pig'],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: '⭐ Amazing memory! The third pig worked for many days to build the strong brick house!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'The third pig was very hard-working and chose heavy bricks. He worked for many days to build a strong house while his brothers played!',
        reminderSegmentId: 's1-p4',
      },
    ],
  },
  {
    id: 'goldilocks',
    title: 'Goldilocks and the Three Bears',
    coverEmoji: '🐻',
    coverGradient: 'from-yellow-300 to-amber-400',
    tagline: 'Just right makes everything nice!',
    ageRange: '4-7',
    readingTime: '5 min',
    difficulty: 'beginner',
    category: 'Classic Tales',
    moral: "Always respect other people's belongings",
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 's2-g1',
        title: 'The Bears Go Walking',
        text: 'Deep in the forest lived three bears — Papa Bear, Mama Bear, and Baby Bear. One morning, Mama Bear made three bowls of porridge for breakfast. But the porridge was too hot to eat! So the three bears went for a walk in the forest to wait for it to cool down. They had no idea that a curious little girl with golden hair was about to visit their house!',
        scene: {
          background: 'from-green-400 to-teal-300',
          foregroundEmojis: '🌲🏡🌲',
          characterLeft: '🐻',
          characterRight: '🐻',
          ambientEmojis: ['🌿', '🌸', '🦌', '☀️'],
        },
      },
      {
        id: 's2-g2',
        title: 'Goldilocks Tries the Porridge',
        text: 'Goldilocks skipped through the forest and found the bears\' little cottage. She knocked on the door — nobody answered! So she peeked inside and walked in. On the table were three bowls of porridge. She tried the big bowl first: "Too hot!" She tried the medium bowl: "Too cold!" Then she tried the tiny bowl: "Mmm, just right!" And she ate it all up!',
        scene: {
          background: 'from-yellow-300 to-orange-200',
          foregroundEmojis: '🥣🍲🥣',
          characterLeft: '👧',
          characterRight: '🥄',
          ambientEmojis: ['✨', '🌟', '💛', '🍯'],
        },
      },
      {
        id: 's2-g3',
        title: 'Goldilocks Tries the Chairs',
        text: 'After eating, Goldilocks saw three chairs. She tried the big chair: "Too hard!" She tried the medium chair: "Too soft!" Then she tried the tiny chair: "Just right!" She sat down happily — but oh no! She was too heavy for Baby Bear\'s little chair, and CRACK! It broke into pieces! Goldilocks felt very sorry.',
        scene: {
          background: 'from-amber-300 to-yellow-200',
          foregroundEmojis: '🪑💺🪑',
          characterLeft: '👧',
          characterRight: '💥',
          ambientEmojis: ['😬', '🌟', '💫', '✨'],
        },
      },
      {
        id: 's2-g4',
        title: 'Goldilocks Finds the Beds',
        text: 'Goldilocks was tired from all her exploring, so she went upstairs. She tried Papa Bear\'s big bed: "Too hard!" She tried Mama Bear\'s medium bed: "Too soft!" Then she tried Baby Bear\'s little bed: "Just right!" She snuggled down under the covers and fell fast asleep, dreaming of honey and flowers.',
        scene: {
          background: 'from-purple-300 to-pink-200',
          foregroundEmojis: '🛏️😴🌙',
          characterLeft: '👧',
          characterRight: '⭐',
          ambientEmojis: ['💤', '🌙', '⭐', '✨'],
        },
      },
      {
        id: 's2-g5',
        title: 'The Bears Come Home!',
        text: 'The three bears came home from their walk. "Someone\'s been eating my porridge!" roared Papa Bear. "Someone\'s been eating MY porridge!" said Mama Bear. "Someone\'s been eating my porridge and ate it ALL UP!" cried Baby Bear. They found the broken chair and then went upstairs. Goldilocks woke up, saw three bears staring at her, jumped out of bed, ran out of the house, and never came back! And she always knocked and waited for an answer after that.',
        scene: {
          background: 'from-orange-400 to-red-300',
          foregroundEmojis: '🐻🐻🐻',
          characterLeft: '👧',
          characterRight: '🐻',
          ambientEmojis: ['😱', '💨', '🌟', '🏃'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q2-gold-1',
        afterSegmentId: 's2-g2',
        question: 'Which bowl of porridge was "just right" for Goldilocks?',
        options: ["Papa Bear's big bowl", "Mama Bear's medium bowl", "Baby Bear's tiny bowl"],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: '🎉 You got it! Baby Bear\'s tiny bowl was just right for Goldilocks!',
        feedbackWrong: "Hmm, let me help you remember...",
        reminderText: "Goldilocks tried all three bowls! Papa Bear's was too hot, Mama Bear's was too cold, and Baby Bear's tiny bowl was just right!",
        reminderSegmentId: 's2-g2',
      },
      {
        id: 'q2-gold-2',
        afterSegmentId: 's2-g4',
        question: "Which bed did Goldilocks sleep in?",
        options: ["Papa Bear's big bed", "Mama Bear's medium bed", "Baby Bear's little bed"],
        correctIndex: 2,
        points: 20,
        feedbackCorrect: "⭐ Wonderful! Baby Bear's little bed was just right for sleeping!",
        feedbackWrong: "Oops! Let me help you remember...",
        reminderText: "Goldilocks tried all three beds! Papa Bear's was too hard, Mama Bear's was too soft, but Baby Bear's little bed was just right — and she fell fast asleep!",
        reminderSegmentId: 's2-g4',
      },
    ],
  },
  {
    id: 'jack-beanstalk',
    title: 'Jack and the Beanstalk',
    coverEmoji: '🌱',
    coverGradient: 'from-green-400 to-emerald-300',
    tagline: 'Dare to climb to the sky!',
    ageRange: '6-10',
    readingTime: '7 min',
    difficulty: 'explorer',
    category: 'Adventure Tales',
    moral: 'Courage and cleverness can overcome great challenges',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 's3-j1',
        title: 'The Magic Beans',
        text: 'Jack and his mother were very poor. Their only treasure was their old cow, Bessie. One day, their mother said they must sell the cow to buy food. On the way to market, Jack met a mysterious old man who offered five magic beans for the cow. Jack made the trade! But when he got home, his mother was so angry that she threw the beans out the window.',
        scene: {
          background: 'from-amber-300 to-yellow-200',
          foregroundEmojis: '🌾🏚️🐄',
          characterLeft: '👦',
          characterRight: '🧓',
          ambientEmojis: ['✨', '💚', '🌟', '🪄'],
        },
      },
      {
        id: 's3-j2',
        title: 'The Giant Beanstalk',
        text: 'The next morning, Jack woke up and couldn\'t believe his eyes! The magic beans had grown into an enormous beanstalk that reached all the way up through the clouds! It was so tall Jack couldn\'t see the top. "I must find out where it goes!" said brave Jack. He grabbed hold of the beanstalk and started climbing, higher and higher and higher!',
        scene: {
          background: 'from-green-400 to-emerald-300',
          foregroundEmojis: '🌱🌿🌳',
          characterLeft: '👦',
          characterRight: '☁️',
          ambientEmojis: ['☁️', '🌤️', '⭐', '🌿'],
        },
      },
      {
        id: 's3-j3',
        title: 'The Giant\'s Castle',
        text: 'At the top of the beanstalk, Jack found a magical land in the clouds! In the distance stood an enormous castle. A kind giantess opened the door and warned Jack that her husband, the terrifying giant, ate boys for breakfast! She hid Jack in the oven just as the giant stomped in, shaking the whole castle. "FEE FI FO FUM!" roared the giant, sniffing the air.',
        scene: {
          background: 'from-purple-400 to-blue-300',
          foregroundEmojis: '☁️🏰☁️',
          characterLeft: '👦',
          characterRight: '👹',
          ambientEmojis: ['☁️', '⭐', '💜', '🌙'],
        },
      },
      {
        id: 's3-j4',
        title: 'The Golden Treasures',
        text: 'The giant counted his bags of gold coins, then fell asleep snoring loudly. Jack crept out and grabbed a bag of gold! He ran to the beanstalk and slid down. His mother was overjoyed! The gold kept them comfortable for a while, but Jack climbed the beanstalk two more times — once to get a magical hen that laid golden eggs, and once to get a golden harp that played music by itself!',
        scene: {
          background: 'from-yellow-400 to-amber-300',
          foregroundEmojis: '🥚🪙🎵',
          characterLeft: '👦',
          characterRight: '🐔',
          ambientEmojis: ['✨', '💛', '⭐', '🌟'],
        },
      },
      {
        id: 's3-j5',
        title: 'The Giant Falls',
        text: 'On his last trip, the giant woke up and chased Jack down the beanstalk! "Help! Mother, bring the axe!" Jack shouted as he scrambled down. His mother threw him the axe and Jack chopped at the beanstalk with all his might. CRASH! Down came the beanstalk and the giant fell away into the clouds, never to be seen again. Jack, his mother, and the magical hen lived happily ever after with plenty of golden eggs!',
        scene: {
          background: 'from-blue-400 to-cyan-300',
          foregroundEmojis: '🌱⚡🏠',
          characterLeft: '👦',
          characterRight: '🪓',
          ambientEmojis: ['🎉', '⭐', '💫', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q3-jack-1',
        afterSegmentId: 's3-j1',
        question: 'What did Jack trade his cow for?',
        options: ['A bag of gold', 'Five magic beans', 'A golden harp'],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 You remembered! Jack traded the cow for five magic beans from a mysterious old man!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'A mysterious old man offered Jack five magic beans in exchange for his cow Bessie. His mother was very angry when Jack came home!',
        reminderSegmentId: 's3-j1',
      },
      {
        id: 'q3-jack-2',
        afterSegmentId: 's3-j4',
        question: 'What magical creature did Jack find in the giant\'s castle that laid golden eggs?',
        options: ['A golden goose', 'A magic hen', 'A rainbow parrot'],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '⭐ Excellent! It was a magical hen that could lay golden eggs!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'In the giant\'s castle, Jack found a magical hen that laid golden eggs! He also found gold coins and a golden harp that played music by itself.',
        reminderSegmentId: 's3-j4',
      },
    ],
  },
  {
    id: 'clever-crow',
    title: 'The Clever Crow',
    coverEmoji: '🦅',
    coverGradient: 'from-blue-400 to-cyan-300',
    tagline: 'Think smart, never give up!',
    ageRange: '5-9',
    readingTime: '4 min',
    difficulty: 'explorer',
    category: 'Wisdom Tales',
    moral: 'Intelligence and patience solve problems',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 's4-c1',
        title: 'A Very Thirsty Crow',
        text: 'On a scorching hot summer day, a clever crow was flying over the fields, desperately searching for water. The sun blazed down and the crow\'s throat was parched and dry. "Water, water, I must find water!" the crow croaked. After searching for a long time, the tired crow finally spotted a tall clay pot sitting in a garden. With hope in his heart, he fluttered down to look inside.',
        scene: {
          background: 'from-orange-400 to-yellow-300',
          foregroundEmojis: '☀️🌿☀️',
          characterLeft: '🦅',
          characterRight: '🏺',
          ambientEmojis: ['☀️', '🌡️', '💦', '🌬️'],
        },
      },
      {
        id: 's4-c2',
        title: 'The Water is Too Low',
        text: 'The crow peeked into the pot and could see water at the bottom — but it was too low for his beak to reach! He tried tilting the pot but it was too heavy. He tried reaching in but his beak was too short. He tried and tried but couldn\'t get a single drop. The crow felt very discouraged. But then he had a wonderful, brilliant idea! He looked around the garden with his sharp, clever eyes.',
        scene: {
          background: 'from-blue-300 to-cyan-200',
          foregroundEmojis: '🏺💧🏺',
          characterLeft: '🦅',
          characterRight: '💭',
          ambientEmojis: ['💡', '💧', '🔵', '✨'],
        },
      },
      {
        id: 's4-c3',
        title: 'The Crow\'s Brilliant Plan',
        text: 'The clever crow spotted small pebbles and stones scattered all around the garden. "Aha!" he cried. One by one, the crow picked up each pebble in his beak and carefully dropped it into the pot. PLOP! PLOP! PLOP! With each pebble that went in, the water rose up just a little bit higher. The crow worked patiently, not giving up even when his wings were tired. Drop by drop, the water was rising!',
        scene: {
          background: 'from-teal-400 to-green-300',
          foregroundEmojis: '🪨💧🪨',
          characterLeft: '🦅',
          characterRight: '🏺',
          ambientEmojis: ['💪', '⭐', '💧', '✨'],
        },
      },
      {
        id: 's4-c4',
        title: 'Sweet Success!',
        text: 'After dropping in many, many pebbles, the water finally rose high enough to reach the crow\'s beak! The crow dipped his beak into the cool, refreshing water and drank deeply. "Ahhhh!" he sighed with joy. Other animals in the garden had been watching in amazement. "How clever!" said a rabbit. "How patient!" said a squirrel. The crow had solved a difficult problem by thinking carefully and never giving up. And from that day on, all the animals called him the Cleverest Crow in the land!',
        scene: {
          background: 'from-cyan-400 to-blue-300',
          foregroundEmojis: '🏺💧🎉',
          characterLeft: '🦅',
          characterRight: '🐰',
          ambientEmojis: ['🎉', '⭐', '💫', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q4-crow-1',
        afterSegmentId: 's4-c2',
        question: 'Why couldn\'t the crow drink the water at first?',
        options: [
          'The water was too dirty',
          'The water was too low in the pot',
          'The pot was empty',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 Brilliant! The water was too low for the crow\'s beak to reach!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'The crow could SEE water in the pot, but it was at the bottom — too low for his beak to reach! He tried tilting the heavy pot but couldn\'t manage it.',
        reminderSegmentId: 's4-c2',
      },
      {
        id: 'q4-crow-2',
        afterSegmentId: 's4-c3',
        question: 'What clever idea did the crow use to raise the water level?',
        options: [
          'He poured more water from a stream',
          'He used a long stick to lift the pot',
          'He dropped pebbles into the pot one by one',
        ],
        correctIndex: 2,
        points: 25,
        feedbackCorrect: '⭐ Perfect! The crow dropped pebbles in one by one to raise the water level — so smart!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'The clever crow spotted pebbles in the garden and had a brilliant idea! He dropped them one by one into the pot. PLOP! PLOP! PLOP! Each pebble made the water rise a little higher!',
        reminderSegmentId: 's4-c3',
      },
    ],
  },
];

  // ── Aesop's Fables ──────────────────────────────────────────────────────
  {
    id: 'tortoise-and-hare',
    title: 'The Tortoise and the Hare',
    coverEmoji: '🐢',
    coverGradient: 'from-green-400 to-teal-300',
    tagline: 'Slow and steady wins the race!',
    ageRange: '4-8',
    readingTime: '4 min',
    difficulty: 'beginner',
    category: "Aesop's Fables",
    moral: 'Slow and steady wins the race — never give up!',
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 'th-1',
        title: 'The Boastful Hare',
        text: 'In a sunny meadow, a hare loved to boast about how fast he could run. He would zoom past all the animals and laugh. "No one is as fast as me!" he bragged every single day. All the animals were tired of his boasting — especially the old tortoise who walked slowly along the path. One morning, the hare ran circles around the tortoise and laughed, "You are SO slow, little shell-back!"',
        scene: {
          background: 'from-green-300 to-lime-200',
          foregroundEmojis: '🌿🌼🌿',
          characterLeft: '🐇',
          characterRight: '🐢',
          ambientEmojis: ['☀️', '🌸', '🦋', '🌿'],
        },
      },
      {
        id: 'th-2',
        title: 'The Big Race',
        text: 'The tortoise looked up calmly and said, "I challenge you to a race!" All the animals gasped. The hare burst out laughing — but he accepted. A fox was chosen as judge. She drew a finish line at the old oak tree on the far hill. "Ready, set, GO!" she shouted. The hare shot off like a rocket, and the tortoise began his slow, steady walk — left foot, right foot, left foot, right foot.',
        scene: {
          background: 'from-yellow-300 to-green-200',
          foregroundEmojis: '🌳🏁🌳',
          characterLeft: '🐢',
          characterRight: '🐇',
          ambientEmojis: ['🎽', '⭐', '🌟', '💨'],
        },
      },
      {
        id: 'th-3',
        title: 'The Hare Takes a Nap',
        text: 'The hare was so far ahead that he stopped under a shady tree. "I am miles ahead!" he yawned. "I have plenty of time for a little nap." He curled up in the cool grass and closed his eyes. Meanwhile, the tortoise kept walking — slowly, steadily, one foot after another. He never stopped. He never rested. He just kept going with a quiet smile on his face.',
        scene: {
          background: 'from-amber-200 to-green-200',
          foregroundEmojis: '🌳😴🌳',
          characterLeft: '🐇',
          characterRight: '💤',
          ambientEmojis: ['💤', '🌙', '🍃', '🌿'],
        },
      },
      {
        id: 'th-4',
        title: 'The Tortoise Wins!',
        text: 'The hare slept much longer than he planned. When he finally woke up and looked at the hill — he could not believe his eyes! The tortoise was just crossing the finish line! All the animals cheered and clapped. The hare ran as fast as he could but it was too late. The tortoise had won! "Congratulations," said the tortoise kindly. "Slow and steady wins the race." The hare never boasted about his speed again.',
        scene: {
          background: 'from-teal-400 to-green-300',
          foregroundEmojis: '🏁🎉🏆',
          characterLeft: '🐢',
          characterRight: '🐇',
          ambientEmojis: ['🎉', '⭐', '🌟', '🏆'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q-th-1',
        afterSegmentId: 'th-2',
        question: 'Why did the hare agree to race the tortoise?',
        options: ['He wanted to make friends', 'He thought he would easily win', 'He was afraid of losing'],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '🎉 Exactly! The hare laughed and thought beating the slow tortoise would be easy!',
        feedbackWrong: 'Hmm, think again...',
        reminderText: 'The hare burst out laughing when the tortoise challenged him. He was so confident in his speed that he accepted right away — he was sure he would win easily!',
        reminderSegmentId: 'th-2',
      },
      {
        id: 'q-th-2',
        afterSegmentId: 'th-3',
        question: 'What did the hare do instead of racing?',
        options: ['He ate some carrots', 'He took a nap under a tree', 'He got lost in the forest'],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '⭐ Right! The hare was so sure he was winning that he stopped for a nap!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'Because he was so far ahead, the hare decided he had time to take a nap under a shady tree. He slept much longer than he planned!',
        reminderSegmentId: 'th-3',
      },
    ],
  },
  {
    id: 'lion-and-mouse',
    title: 'The Lion and the Mouse',
    coverEmoji: '🦁',
    coverGradient: 'from-yellow-400 to-amber-300',
    tagline: 'Even small friends can help!',
    ageRange: '4-8',
    readingTime: '4 min',
    difficulty: 'beginner',
    category: "Aesop's Fables",
    moral: 'Even the smallest friend can be a great help',
    pointsReward: 50,
    requiredLevel: 0,
    segments: [
      {
        id: 'lm-1',
        title: 'The Lion Naps',
        text: 'In the heart of a great jungle, the mighty lion — king of all animals — was sleeping peacefully under a wide acacia tree. His golden mane spread out like a crown. All the animals tiptoed past, careful not to wake him. But a tiny mouse was not paying attention. She scurried this way and that, collecting seeds — and ran right across the lion\'s enormous paw!',
        scene: {
          background: 'from-yellow-300 to-amber-200',
          foregroundEmojis: '🌳😴🌳',
          characterLeft: '🦁',
          characterRight: '🐭',
          ambientEmojis: ['☀️', '🌿', '🌸', '🍃'],
        },
      },
      {
        id: 'lm-2',
        title: 'Caught!',
        text: 'The lion woke with a great ROAR! He slapped his enormous paw down and caught the tiny mouse. The little mouse trembled with fright. "Please, great King!" she squeaked. "Let me go! I didn\'t mean to wake you! Spare me, and one day I shall repay you!" The lion looked at the tiny creature and laughed his big booming laugh. "You? Repay ME — the King of the Jungle? How funny!" But he was so amused that he opened his paw and let the little mouse go free.',
        scene: {
          background: 'from-orange-400 to-yellow-300',
          foregroundEmojis: '🦁🐭✨',
          characterLeft: '🦁',
          characterRight: '🐭',
          ambientEmojis: ['😱', '💫', '🌟', '❤️'],
        },
      },
      {
        id: 'lm-3',
        title: 'The Lion is Trapped!',
        text: 'Some days later, the lion was prowling through the jungle when — SNAP! He stepped into a hunter\'s net! The more he struggled, the tighter the ropes became. He roared and roared so loudly that the whole jungle shook with fear. But no animal was brave enough to help the mighty lion. Then the little mouse heard his cries. She remembered his kindness and ran as fast as her tiny legs could carry her.',
        scene: {
          background: 'from-red-400 to-orange-300',
          foregroundEmojis: '🕸️🦁🕸️',
          characterLeft: '🦁',
          characterRight: '🏹',
          ambientEmojis: ['😰', '💔', '🌿', '🍃'],
        },
      },
      {
        id: 'lm-4',
        title: 'The Mouse Saves the Day',
        text: 'The little mouse found the lion tangled in the net. Without a moment\'s hesitation, she began gnawing the thick ropes with her sharp little teeth. Gnaw, gnaw, gnaw! One by one, the ropes snapped apart. Soon the lion was free! He stretched and shook his great mane. "Little mouse," he said gently, "I laughed when you said you would repay me. I was wrong. A small friend is a great friend indeed." And the lion and the mouse were the best of friends for the rest of their days.',
        scene: {
          background: 'from-green-400 to-teal-300',
          foregroundEmojis: '🦁🐭🎉',
          characterLeft: '🐭',
          characterRight: '🦁',
          ambientEmojis: ['🎉', '⭐', '💚', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q-lm-1',
        afterSegmentId: 'lm-2',
        question: 'Why did the lion let the mouse go free?',
        options: [
          'The mouse was too small to eat',
          'The mouse made the lion laugh and he felt kind',
          'The lion was afraid of the mouse',
        ],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '🎉 Yes! The mouse made the lion laugh, and in his good mood he decided to let her go!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'The lion laughed at the idea that a tiny mouse could ever repay him — but her funny promise amused him so much that he opened his paw and let her go free.',
        reminderSegmentId: 'lm-2',
      },
      {
        id: 'q-lm-2',
        afterSegmentId: 'lm-4',
        question: 'How did the mouse rescue the lion?',
        options: [
          'She called the other animals for help',
          'She chewed through the ropes with her teeth',
          'She scared away the hunters',
        ],
        correctIndex: 1,
        points: 20,
        feedbackCorrect: '⭐ Brilliant! The mouse used her sharp little teeth to gnaw through every rope!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'The little mouse gnawed through the thick ropes of the hunter\'s net with her sharp teeth — one by one until the lion was completely free!',
        reminderSegmentId: 'lm-4',
      },
    ],
  },
  {
    id: 'little-red-riding-hood',
    title: 'Little Red Riding Hood',
    coverEmoji: '🧺',
    coverGradient: 'from-red-400 to-pink-300',
    tagline: 'Stay on the path and trust the truth!',
    ageRange: '5-9',
    readingTime: '6 min',
    difficulty: 'explorer',
    category: "Grimm's Fairy Tales",
    moral: 'Listen to your elders and never talk to strangers',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 'rr-1',
        title: 'The Girl with the Red Hood',
        text: 'Once upon a time, a sweet little girl lived near a great forest. She was loved by everyone who knew her. Her grandmother had sewn her a beautiful red riding hood, and the girl wore it so often that everyone called her Little Red Riding Hood. One morning, her mother packed a basket of fresh bread, butter, and sweet cakes. "Your grandmother is feeling poorly," said her mother. "Take this to her — but stay on the path, and do not stop to talk to strangers!"',
        scene: {
          background: 'from-green-300 to-emerald-200',
          foregroundEmojis: '🌳🏡🌳',
          characterLeft: '👧',
          characterRight: '🧺',
          ambientEmojis: ['🌸', '🦋', '☀️', '🌿'],
        },
      },
      {
        id: 'rr-2',
        title: 'The Wolf in the Forest',
        text: 'Little Red Riding Hood skipped happily into the forest. The birds sang and the sun shone through the leaves. But soon she met a big grey wolf standing in her path. "Good morning, little girl!" he said with a wide grin. "Where are you going with that lovely basket?" Little Red Riding Hood forgot her mother\'s warning. "To Grandmother\'s cottage on the other side of the forest!" she said. The wolf smiled an even wider smile and had a very wicked plan.',
        scene: {
          background: 'from-green-400 to-teal-300',
          foregroundEmojis: '🌲🐺🌲',
          characterLeft: '👧',
          characterRight: '🐺',
          ambientEmojis: ['🍃', '🌿', '🦅', '🌙'],
        },
      },
      {
        id: 'rr-3',
        title: 'The Wolf Tricks Grandmother',
        text: 'The cunning wolf knew a shortcut! He raced through the trees and arrived at Grandmother\'s cottage long before Little Red Riding Hood. He knocked on the door. "Who is there?" called a frail voice. "It\'s me, Little Red Riding Hood, Grandmother!" the wolf said in a sweet, high voice. The door opened, and the wolf burst inside. He locked poor Grandmother in the wardrobe, then pulled on her spare nightgown and cap and jumped into her bed, pulling the covers up to his snout.',
        scene: {
          background: 'from-purple-300 to-pink-200',
          foregroundEmojis: '🏡🐺🛏️',
          characterLeft: '🐺',
          characterRight: '👵',
          ambientEmojis: ['😱', '🌙', '🍃', '⚠️'],
        },
      },
      {
        id: 'rr-4',
        title: 'What Big Eyes You Have!',
        text: 'Little Red Riding Hood arrived and knocked. "Come in, dear!" growled the wolf in his best grandmother voice. She walked in and something felt very strange. She crept closer to the bed. "Grandmother, what big eyes you have!" "All the better to see you with, my dear!" "What big ears you have!" "All the better to hear you with!" "What big TEETH you have!" "All the better to EAT you with!" And the wolf leapt from the bed! Little Red Riding Hood screamed and ran for the door!',
        scene: {
          background: 'from-red-400 to-orange-300',
          foregroundEmojis: '🛏️😱🐺',
          characterLeft: '👧',
          characterRight: '🐺',
          ambientEmojis: ['😱', '💨', '⚡', '🚪'],
        },
      },
      {
        id: 'rr-5',
        title: 'Saved by the Woodcutter',
        text: 'A brave woodcutter was passing the cottage when he heard screaming. He burst through the door with his axe! The wolf took one look at the woodcutter and ran out of the cottage and deep into the forest, never to return. The woodcutter freed Grandmother from the wardrobe, safe and well. Little Red Riding Hood hugged her grandmother tightly. "I should have listened to Mother and stayed on the path," she said. From that day on, she always did exactly what her mother told her.',
        scene: {
          background: 'from-green-400 to-emerald-300',
          foregroundEmojis: '🪓🏡🎉',
          characterLeft: '🪓',
          characterRight: '👧',
          ambientEmojis: ['🎉', '❤️', '⭐', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q-rr-1',
        afterSegmentId: 'rr-2',
        question: "What did Little Red Riding Hood's mother tell her NOT to do?",
        options: [
          'Pick flowers in the forest',
          'Talk to strangers and leave the path',
          'Run too fast to grandmother\'s house',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 Correct! Her mother said stay on the path and never talk to strangers!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'Her mother said clearly: "Stay on the path, and do not stop to talk to strangers!" — but Little Red Riding Hood forgot this warning when she met the wolf.',
        reminderSegmentId: 'rr-2',
      },
      {
        id: 'q-rr-2',
        afterSegmentId: 'rr-4',
        question: 'What had the wolf done with Grandmother?',
        options: [
          'Sent her to pick flowers',
          'Locked her in the wardrobe',
          'Chased her out of the cottage',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '⭐ Yes! The sneaky wolf locked Grandmother in the wardrobe and took her place in bed!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'When the wolf arrived at Grandmother\'s cottage, he locked poor Grandmother safely in the wardrobe, then disguised himself in her nightgown and cap and got into her bed.',
        reminderSegmentId: 'rr-4',
      },
    ],
  },
  {
    id: 'ugly-duckling',
    title: 'The Ugly Duckling',
    coverEmoji: '🦢',
    coverGradient: 'from-blue-400 to-cyan-300',
    tagline: 'You are beautiful just as you are!',
    ageRange: '5-9',
    readingTime: '7 min',
    difficulty: 'explorer',
    category: "Hans Christian Andersen",
    moral: 'Everyone blossoms in their own time — be kind to those who are different',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 'ud-1',
        title: 'The Strange Egg',
        text: 'In a cosy nest beside a quiet pond, a mother duck sat on her eggs waiting for them to hatch. One by one, the eggs cracked open and fluffy yellow ducklings popped out, cheeping with delight. But one egg — the largest one — had not hatched yet. At last it cracked open, and out tumbled a duckling. But this one was big and grey and awkward. "Oh my," said the mother duck softly. "You do look a little different, my dear."',
        scene: {
          background: 'from-green-300 to-teal-200',
          foregroundEmojis: '🌿🥚🌿',
          characterLeft: '🦆',
          characterRight: '🐣',
          ambientEmojis: ['🌸', '☀️', '🦋', '💧'],
        },
      },
      {
        id: 'ud-2',
        title: 'Nobody Wants to Play',
        text: 'The other ducklings were not kind. "You are too big!" they quacked. "You are too grey! You are ugly!" The hens pecked at him. The geese honked at him. Even the children at the farmyard laughed and pointed. The poor duckling felt very sad and alone. He tried to swim with the others but they splashed away. He tried to eat with the others but they pushed him out. No matter what he did, he did not belong.',
        scene: {
          background: 'from-amber-300 to-yellow-200',
          foregroundEmojis: '🦆🦆🦆',
          characterLeft: '🐥',
          characterRight: '🦆',
          ambientEmojis: ['😢', '💧', '🍃', '🌧️'],
        },
      },
      {
        id: 'ud-3',
        title: 'A Long Cold Winter',
        text: 'The duckling ran away to live alone in the marshes. One evening he saw a flock of magnificent birds flying overhead — so white, so graceful, so beautiful. He did not know what they were, but he felt a strange longing in his heart. Winter came and the cold was bitter. The duckling nearly froze in the ice. A kind farmer found him and brought him inside, but his noisy children scared the duckling so much that he flew out the window and lived alone through the long, cold winter.',
        scene: {
          background: 'from-blue-300 to-indigo-200',
          foregroundEmojis: '❄️🌙❄️',
          characterLeft: '🐥',
          characterRight: '🦢',
          ambientEmojis: ['❄️', '🌨️', '💨', '⭐'],
        },
      },
      {
        id: 'ud-4',
        title: 'A Beautiful Surprise',
        text: 'Spring came at last. The duckling stretched his wings — they were huge and strong! He flew over the meadows until he came to a beautiful lake. There in the water were those magnificent white birds. Trembling, he landed nearby, expecting to be chased away again. He bowed his head and saw his reflection in the water for the first time. He was not a grey duckling at all! He was a beautiful, graceful white swan! The other swans swam right over and welcomed him warmly. Children who saw him cried, "Look — the newest swan is the most beautiful of all!"',
        scene: {
          background: 'from-cyan-400 to-blue-300',
          foregroundEmojis: '🦢💧🦢',
          characterLeft: '🦢',
          characterRight: '🌸',
          ambientEmojis: ['🌸', '⭐', '💫', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q-ud-1',
        afterSegmentId: 'ud-2',
        question: 'Why did the other ducklings tease the ugly duckling?',
        options: [
          'Because he was too slow at swimming',
          'Because he was big and grey and looked different',
          'Because he ate too much food',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 Right! They teased him because he looked different — bigger and greyer than the others.',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'The other ducklings called him too big and too grey. The hens pecked him and even the children laughed. He was teased because he simply looked different from everyone else.',
        reminderSegmentId: 'ud-2',
      },
      {
        id: 'q-ud-2',
        afterSegmentId: 'ud-4',
        question: 'What did the duckling discover about himself at the lake?',
        options: [
          'That he was the fastest swimmer of all',
          'That he was actually a beautiful swan',
          'That he had magical powers',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '⭐ Wonderful! He saw his reflection and realised he was a beautiful swan all along!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'When the duckling looked at his reflection in the lake, he saw that he was not ugly at all — he had grown into a magnificent white swan, the most beautiful one at the lake!',
        reminderSegmentId: 'ud-4',
      },
    ],
  },
  {
    id: 'cinderella',
    title: 'Cinderella',
    coverEmoji: '👠',
    coverGradient: 'from-blue-400 to-purple-300',
    tagline: 'Kindness is always rewarded!',
    ageRange: '6-10',
    readingTime: '8 min',
    difficulty: 'explorer',
    category: "Grimm's Fairy Tales",
    moral: 'Kindness and goodness are more beautiful than riches',
    pointsReward: 75,
    requiredLevel: 1,
    segments: [
      {
        id: 'cin-1',
        title: 'A Sad and Lonely Life',
        text: 'Once there was a kind and gentle girl whose mother had died. Her father remarried a proud, cold woman who had two daughters of her own. From the day they moved in, life changed for the girl. She was made to cook, clean, and scrub from morning to night. When her chores were done, she would sit by the hearth in the cinders to keep warm. Her step-sisters laughed and called her Cinderella. But no matter how badly they treated her, Cinderella always remained kind.',
        scene: {
          background: 'from-gray-400 to-stone-300',
          foregroundEmojis: '🏠🔥🏠',
          characterLeft: '👧',
          characterRight: '🧹',
          ambientEmojis: ['🍂', '🌙', '💫', '🌿'],
        },
      },
      {
        id: 'cin-2',
        title: 'The Royal Ball',
        text: 'One day, an invitation arrived from the royal palace. The Prince was hosting a grand ball, and every young lady in the kingdom was invited! Cinderella\'s step-sisters screamed with excitement and ordered Cinderella to do their hair, iron their gowns, and lace their shoes. When Cinderella asked if she might go too, they all laughed. "You? In those rags?" said her stepmother. When they left for the ball, Cinderella sat alone and wept.',
        scene: {
          background: 'from-purple-400 to-pink-300',
          foregroundEmojis: '💌🏰💌',
          characterLeft: '👧',
          characterRight: '📜',
          ambientEmojis: ['💜', '✨', '🌙', '💫'],
        },
      },
      {
        id: 'cin-3',
        title: 'The Fairy Godmother',
        text: 'Suddenly, a warm golden light filled the kitchen. An old woman with a kind face and a sparkling wand appeared. "Dry your tears, my dear," she said. "I am your Fairy Godmother!" With a wave of her wand, a pumpkin became a gleaming golden coach. Six mice became magnificent white horses. Cinderella\'s rags transformed into a dazzling silver gown, and on her feet appeared the most delicate glass slippers. "Go to the ball," said the Fairy Godmother, "but be home before midnight — for at the last stroke of twelve, the magic ends!"',
        scene: {
          background: 'from-yellow-400 to-amber-300',
          foregroundEmojis: '✨🎃✨',
          characterLeft: '🧙‍♀️',
          characterRight: '👠',
          ambientEmojis: ['✨', '⭐', '💫', '🌟'],
        },
      },
      {
        id: 'cin-4',
        title: 'Dancing with the Prince',
        text: 'At the palace, everyone stopped and stared as Cinderella walked in. She was the most beautiful person anyone had ever seen. The Prince came straight to her and bowed. "May I have this dance?" he asked. They danced together all evening, and Cinderella felt as though she were floating on a cloud. The Prince never left her side. But then — DONG! The clock began to strike midnight! Cinderella gasped and ran from the ballroom!',
        scene: {
          background: 'from-blue-400 to-indigo-300',
          foregroundEmojis: '🏰💃🏰',
          characterLeft: '👸',
          characterRight: '🤴',
          ambientEmojis: ['✨', '💙', '⭐', '🕛'],
        },
      },
      {
        id: 'cin-5',
        title: 'The Glass Slipper',
        text: 'Cinderella flew down the palace steps — and in her hurry, one glass slipper came off! She couldn\'t stop. By the last stroke of midnight her gown was rags again. But the Prince had found the tiny glass slipper. He declared that he would marry whoever the slipper fit. His messengers searched the whole kingdom. The step-sisters pushed and squeezed, but the slipper would not fit. Then Cinderella stepped forward. The slipper slid on perfectly. The Prince recognised her eyes and smiled. Cinderella and the Prince were married, and she forgave her step-family. They all lived happily ever after.',
        scene: {
          background: 'from-blue-300 to-purple-200',
          foregroundEmojis: '👠🤴👠',
          characterLeft: '👸',
          characterRight: '🤴',
          ambientEmojis: ['🎉', '❤️', '⭐', '🌟'],
        },
      },
    ],
    quizzes: [
      {
        id: 'q-cin-1',
        afterSegmentId: 'cin-3',
        question: "What did the Fairy Godmother use to make Cinderella's golden coach?",
        options: ['A golden box', 'A pumpkin', 'A wooden cart'],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '🎉 That\'s right! With a wave of her wand, a pumpkin became a gleaming golden coach!',
        feedbackWrong: 'Hmm, let me help you remember...',
        reminderText: 'The Fairy Godmother waved her wand and a pumpkin from the garden transformed into a beautiful golden coach for Cinderella to ride to the ball!',
        reminderSegmentId: 'cin-3',
      },
      {
        id: 'q-cin-2',
        afterSegmentId: 'cin-5',
        question: 'How did the Prince find Cinderella after the ball?',
        options: [
          'He asked her step-sisters for her address',
          'He fitted the glass slipper she left behind',
          'He followed her carriage home',
        ],
        correctIndex: 1,
        points: 25,
        feedbackCorrect: '⭐ Perfect! She left behind a glass slipper and only her foot could fit it!',
        feedbackWrong: 'Oops! Let me help you remember...',
        reminderText: 'When Cinderella fled at midnight, one glass slipper fell off on the steps. The Prince searched the whole kingdom for the girl whose foot fit the tiny slipper — and it was Cinderella!',
        reminderSegmentId: 'cin-5',
      },
    ],
  },
];

export function getStoryById(id: string): Story | undefined {
  return STORIES.find((s) => s.id === id);
}
